'use strict';
const assert=require('assert'),crypto=require('crypto'),fs=require('fs'),os=require('os'),path=require('path'),{spawnSync}=require('child_process');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
assert.equal(read('moyu/VERSION').trim(),'1.11.2');
const index=read('moyu/index.html'),visual=read('moyu/visual-v1112.css'),manifest=read('moyu/SOURCE_SHA256').trim().split(/\r?\n/),parts=Array.from({length:15},(_,i)=>read(`moyu/src/game.part${String(i+1).padStart(2,'0')}.js`)),base=parts.join('');
const expected=Object.fromEntries(manifest.map(x=>{const [h,f]=x.split(/\s+/);return[f,h]})),digest=x=>crypto.createHash('sha256').update(x).digest('hex');
assert.equal(digest(base),expected['base-game.js']);
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'moyu1112-')),js=path.join(tmp,'game.js');fs.writeFileSync(js,base);
let r=spawnSync('patch',['--silent',js],{input:read('moyu/patches/runtime-v1111.patch'),encoding:'utf8'});assert.equal(r.status,0,r.stderr);
assert.equal(digest(fs.readFileSync(js,'utf8')),expected['game-v1111.js']);
r=spawnSync('patch',['--silent',js],{input:read('moyu/patches/runtime-v1112.patch'),encoding:'utf8'});assert.equal(r.status,0,r.stderr);
const game=fs.readFileSync(js,'utf8');
assert.match(index,/content="1\.11\.2"/);assert.match(index,/style\.css\?v=1112/);assert.match(index,/visual-v1112\.css\?v=1112/);assert.match(index,/game\.js\?v=1112/);
assert.match(game,/dataset\.gameVersion='1\.11\.2'/);assert.match(game,/DAY_END_DISTANCE=2200/);assert.match(game,/PLAYER_HIT=\{left:10,right:10,top:7,bottom:6\}/);assert.match(game,/groundTakeoff=before===0/);
assert.match(game,/readSharedLangCookie/);assert.match(game,/writeSharedLangCookie\(currentLang\)/);assert.match(game,/home\.searchParams\.set\('lang',currentLang\)/);
assert.doesNotMatch(game,/drawPlayerFocus\(drawX,footY,altitude\);/);assert.doesNotMatch(game,/drawBackground\(\);drawAmbientOfficeLife\(\);drawRunAtmosphere\(\);/);
assert.match(visual,/min-width:60px/);assert.match(visual,/\.tagline\{font-size:15px/);assert.match(visual,/\.controls\{font-size:12\.5px/);assert.match(visual,/\.card\{width:min\(700px,92%\)/);
r=spawnSync(process.execPath,['--check',js],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);
const archive=path.join(tmp,'moyu.zip');r=spawnSync('bash',[path.join(root,'ops/release/build-moyu-bundle.sh'),archive],{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/version=1\.11\.2/);assert.match(r.stdout,/moyu_bundle_build=PASS/);
r=spawnSync('unzip',['-p',archive,'public/moyu/index.html'],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/visual-v1112\.css\?v=1112/);
r=spawnSync('unzip',['-Z1',archive],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);for(const f of ['public/moyu/index.html','public/moyu/style.css','public/moyu/visual-v1112.css','public/moyu/game.js','public/moyu/VERSION'])assert(r.stdout.includes(f),`bundle missing ${f}`);
fs.rmSync(tmp,{recursive:true,force:true});console.log('RESULT  Clock Out Alive v1.11.2 locale/readability contract PASS');
