'use strict';

const assert=require('assert');
const crypto=require('crypto');
const fs=require('fs');
const os=require('os');
const path=require('path');
const {spawnSync}=require('child_process');

const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const version=read('moyu/VERSION').trim();
const html=read('moyu/index.html');
const css=read('moyu/style.css');
const manifest=read('moyu/SOURCE_SHA256');
const parts=fs.readdirSync(path.join(root,'moyu/src')).filter(n=>/^game\.part\d{2}\.js$/.test(n)).sort();
assert.equal(version,'1.11.0');
assert.equal(parts.length,15);
const game=parts.map(n=>read('moyu/src/'+n)).join('');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const expected=name=>manifest.split(/\r?\n/).find(l=>l.trim().endsWith('  '+name))?.trim().split(/\s+/)[0];
assert.equal(sha(html),expected('index.html'),'index checksum drift');
assert.equal(sha(game),expected('game.js'),'reconstructed game checksum drift');
assert.match(html,/style\.css\?v=1110/);
assert.match(html,/game\.js\?v=1110/);
assert.match(html,/meta name="version" content="1\.11\.0"/);
assert.match(game,/dataset\.gameVersion='1\.11\.0'/);
assert.match(game,/DAY_END_DISTANCE=2200/);
assert.match(game,/PLAYER_HIT=\{left:10,right:10,top:7,bottom:6\}/);
assert.match(game,/'老板':\{w:60,h:92\}/);
assert.match(game,/'会议':\{w:136,h:210/);
assert.match(game,/const LANG_KEY='91hwl_lang'/);
assert.match(game,/pointerdown/);
assert.match(css,/safe-area-inset-bottom/);
assert.match(css,/@media\(pointer:coarse\)/);
assert.match(css,/touch-action:none/);
assert.doesNotMatch(html,/v1\.11 RC4/);

const temp=fs.mkdtempSync(path.join(os.tmpdir(),'moyu-release-'));
const js=path.join(temp,'game.js');fs.writeFileSync(js,game);
let result=spawnSync(process.execPath,['--check',js],{encoding:'utf8'});
assert.equal(result.status,0,result.stderr);
const archive=path.join(temp,'moyu.zip');
result=spawnSync('bash',[path.join(root,'ops/release/build-moyu-bundle.sh'),archive],{cwd:root,encoding:'utf8'});
assert.equal(result.status,0,result.stderr);
assert.match(result.stdout,/version=1\.11\.0/);
assert.match(result.stdout,new RegExp('game_sha256='+expected('game.js')));
result=spawnSync('unzip',['-Z1',archive],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);
const files=result.stdout.trim().split(/\r?\n/);
for(const f of ['VERSION','REVISION','SHA256SUMS','ops/deploy.sh','ops/healthcheck.sh','public/moyu/index.html','public/moyu/style.css','public/moyu/game.js','public/moyu/VERSION'])assert(files.includes(f),`bundle missing ${f}`);
fs.rmSync(temp,{recursive:true,force:true});
console.log('RESULT  Clock Out Alive v1.11.0 release contract PASS');
