'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const html=read('wildforge/index.html'),css=read('wildforge/style.css'),game=read('wildforge/src/game.js'),world=read('wildforge/src/world.js'),data=read('wildforge/src/data.js');
assert.equal(read('wildforge/VERSION').trim(),'0.8.0');
assert(html.includes('<meta name="version" content="0.8.0"'));
assert(data.includes("VERSION = '0.8.0'"));
assert(game.includes("const SAVE_KEY = 'wildforge.save.v080'"));
assert(html.includes('<meta name="version" content="0.8.0"'));assert(html.includes('id="victoryScreen"')&&html.includes('id="continueAfterVictory"'),'v0.3 finale UI missing');
for(const marker of ['id="game"','id="hotbar"','id="mobileControls"','id="portraitGuard"','id="inventoryPanel"','id="fullscreenBtn"']) assert(html.includes(marker),'missing '+marker);
assert(css.includes('@media (orientation:portrait)')&&css.includes('@media (max-height:520px) and (orientation:landscape)'),'landscape-first responsive contract missing');
assert(game.includes("screen.orientation.lock('landscape')"),'fullscreen landscape lock missing');
assert(game.includes("if(e.pointerType!=='touch')"),'touch canvas tap must aim without auto-mining');
assert(game.includes('mobileDirected?mobileAimPenalty(base.x,base.y):-.4'),'touch tap keeps exact-solid priority while joystick aim becomes directional');

for(const behavior of ['function mine(dt)','function place(','function craft(r)','function updateEnemies(dt)','function saveGame(show=true)','function respawn()','function spawnDrop(','function updateDrops(dt)','function drawLighting()','function updateProgression(dt)']) assert(game.includes(behavior),'runtime behavior missing: '+behavior);
assert(game.includes('jumpBuffer')&&game.includes('coyote'),'movement forgiveness missing');
assert(game.includes('moveAxis:{x:0,y:0,touch:false}')&&game.includes('targetVx=dir*max'),'analog movement speed missing');
assert(game.includes('jumpHold=.17')&&game.includes('p.vy*=.57'),'variable jump height missing');
assert(game.includes('function tryStepUp')&&game.includes('landingKick'),'step assist / landing feel missing');
assert(game.includes('function stableMineTarget')&&game.includes('function bridgeAssistTarget'),'continuous mine/build assist missing');
assert(game.includes('function sfx(kind,intensity=1)')&&game.includes('ensureAudio()'),'procedural interaction sound feedback missing');
assert(game.includes("game.pointer.kind==='touch'")&&game.includes("reachTarget(mode='aim')"),'touch target assist missing');
assert(game.includes('DEPTH_ZONES')&&game.includes("id:'star'"),'depth progression missing');
for(const worldRule of ['carveCaves(rng)','scatterOre(rng','placeTrees(rng)','placeGlowMoss(rng)','placeRuins(rng)']) assert(world.includes(worldRule),'world rule missing: '+worldRule);
const tileEntries=(data.match(/solid:(?:true|false)/g)||[]).length;
const recipeEntries=(data.match(/\{id:'[^']+',out:\{id:/g)||[]).length;
const enemyEntries=(data.match(/hp:\d+,damage:\d+,speed:/g)||[]).length;
assert(tileEntries>=24,'expected at least 24 tile/material definitions');
assert(recipeEntries>=22,'expected at least 19 craft recipes');
assert(enemyEntries>=6,'expected six enemy families including the finale boss');
assert(data.includes('RELIC_CHEST:23')&&world.includes('TILE.RELIC_CHEST'),'relic cache world content missing');
assert(data.includes("ancient_core:{id:'ancient_core'")&&data.includes("sentinel_blade:{id:'sentinel_blade'")&&data.includes("delver_pick:{id:'delver_pick'"),'relic loot identity missing');
assert(game.includes('function tryOpenRelicChest(t)')&&game.includes('guardianDefeated'),'guarded relic-cache runtime missing');
assert(data.includes('STAR_FORGE:28')&&data.includes("id:'star_forge'")&&data.includes("rift_beast:{zh:'裂隙巨兽'"),'v0.3 finale content missing');
assert(game.includes('function igniteForge(t,dt)')&&game.includes('function spawnRiftBeast(t)')&&game.includes('bossDefeated')&&game.includes('continueAfterVictory'),'v0.3 finale runtime missing');
assert(data.includes("id:'arrow'")&&data.includes("id:'wood_bow'")&&data.includes("id:'crystal_bow'"),'v0.4 ranged content missing');
assert(game.includes('function updateProjectiles(dt)')&&game.includes('weapon.ranged')&&game.includes('drawProjectiles'),'v0.4 ranged runtime missing');
assert(data.includes('RUIN_SPIKE:24')&&world.includes('TILE.RUIN_SPIKE')&&game.includes('function updateHazards()'),'ruin spike hazard missing');
assert(game.includes('function updateRelicHint(dt)')&&game.includes('RELIC SIGNAL'),'relic resonance guidance missing');

for(const marker of ['TILE.RELIC_CHEST','function tryOpenRelicChest(t)','function spawnChestGuardian(t,key)','function openRelicChest(t,key)','ancient_core','sentinel_blade','delver_pick','specialCd:1.1','e.windup=.62','e.charge=.34']) assert((game+data+world).includes(marker),'relic exploration contract missing: '+marker);
assert(world.includes('this.ruins.push({x,y,w:rw,h:rh,biome:b,chestX,chestY})'),'ruin chest metadata missing');
assert(world.includes('TILE.RUIN_URN')&&game.includes('function breakRuinUrn(t)'),'breakable ruin urn exploration prop missing');
assert(data.includes('ROPE:26')&&data.includes("rope:{id:'rope'")&&game.includes('playerTouchesTile(TILE.ROPE)'),'climbable rope tool missing');
assert(data.includes('PLATFORM:27')&&data.includes("id:'platform'")&&game.includes('platformLandingY')&&game.includes('applyFallDamage'),'one-way platform and fall-risk loop missing');
assert(game.includes('campRespawn')&&game.includes('safeCampPoint')&&game.includes('前哨营地已绑定'),'camp return loop missing');
assert(html.includes('id="moveStick"')&&html.includes('id="aimStick"')&&html.includes('id="mobilePlace"')&&html.includes('id="mobileTorch"'),'dual-stick landscape touch controls missing');
assert(game.includes("canvas.addEventListener('wheel'")&&game.includes('game.smartCursor=!game.smartCursor')&&game.includes('game.autoTool=true'),'desktop native-sandbox input helpers missing');
assert(game.includes("setupStick($('#moveStick')")&&game.includes("setupStick($('#aimStick')")&&game.includes('syncMobileAim()'),'analog touch runtime missing');
assert(game.includes("game.quickPlaceId='torch'")&&game.includes("game.autoTool&&count('torch')>0?'torch'"),'quick torch input missing');
assert(game.includes('miningSwing=game.input.mine')&&game.includes('pointerWorld():{x:game.player.x+game.player.facing*2'),'aim-following tool swing missing');
for(const protectedName of ['Creeper','Zombie','Slime King','Eye of Cthulhu','Netherite','Enderman']) assert(!html.includes(protectedName)&&!data.includes(protectedName),'copied game identity found: '+protectedName);
const combined=html+css+game+world+data;for(const foreign of ['../moyu/','../board-games/','../game/core/','/moyu/','/board-games/'])assert(!combined.includes(foreign),'Wildforge crosses game boundary: '+foreign);
const catalog=JSON.parse(read('games.json'));assert(!catalog.games.some(g=>g.id==='wildforge'),'incubating Wildforge must not enter public catalog before promotion');

assert(game.includes('function tryDash()')&&game.includes('dashCooldown')&&game.includes('dashTimer'),'v0.5 dodge runtime missing');
assert(game.includes('function updateEnemyProjectiles(dt)')&&game.includes('function spawnEnemyProjectile(e)'),'reactive enemy projectile runtime missing');
assert(game.includes("e.type==='hollow_wisp'")&&game.includes('幽光弹'),'hollow wisp ranged behavior missing');
assert(game.includes("if(game.player?.dashTimer>0&&amount<999)return;"),'dash i-frames missing');
assert(html.includes('id="mobileDash"'),'mobile dash control missing');
assert(game.includes("e.code==='KeyQ'")&&game.includes("$('#mobileDash')"),'dash input contract missing');

assert(data.includes("VERSION = '0.8.0'"),'data module version must match incubation build');
assert(game.includes("const SAVE_KEY = 'wildforge.save.v080'"),'v0.8 save key missing');
assert(game.includes('function nightPhase()')&&game.includes('function updateWorldRhythm(dt)'),'day/night rhythm runtime missing');
assert(game.includes('nightSurge')&&game.includes('nightsSurvived'),'night survival state missing');
assert(game.includes('LEGACY_SAVE_KEY_OLDEST')&&game.includes('for(const key of [SAVE_KEY,LEGACY_SAVE_KEY,LEGACY_SAVE_KEY_060,LEGACY_SAVE_KEY_OLD,LEGACY_SAVE_KEY_OLDER,LEGACY_SAVE_KEY_OLDEST])'),'new-world reset must clear all legacy saves');
assert(game.includes('campfireDistance')&&game.includes('fireDist<4.1&&!e.elite'),'campfire ward missing');
assert(game.includes("game.nightState==='night'?3.1:2.4"),'night campfire healing boost missing');
assert(game.includes('game.rng()<.46')&&game.includes("type==='hollow_wisp"),'night wisp weighting missing');
assert(html.includes('id="dangerText"'),'night danger HUD marker missing');
assert(css.includes('#dangerText.active')&&css.includes('#dangerText.warning'),'night danger HUD styling missing');
console.log(`wildforge_v080=PASS tiles=${tileEntries} recipes=${recipeEntries} enemies=${enemyEntries}`);

assert(game.includes("const SAVE_KEY = 'wildforge.save.v080'"),'v0.8 save key missing');
assert(game.includes('outpostReady'),'outpost readiness state missing');
assert(game.includes('outpost salvage')&&game.includes('日出 · 守夜'),'dawn outpost salvage feedback missing');
assert(game.includes("Math.round(amount*.72)")&&game.includes("!['ruin_sentinel','rift_beast'].includes(source)"),'outpost ward damage mitigation must exclude elite/boss damage');
assert(game.includes("campfireDistance(p.x,p.y)<4.1"),'campfire ward must intercept enemy projectiles');
assert(game.includes('LEGACY_SAVE_KEY_OLDEST'),'legacy save chain missing');
assert(game.includes('LEGACY_SAVE_KEY_060')&&game.includes("raw.v==='0.7.0'"),'v0.7 migration chain missing');
assert(game.includes('worldProgress')&&game.includes('markBiomeVisited')&&game.includes('markRelicBiome'),'persistent world memory missing');
assert(game.includes('worldProgress:game.worldProgress'),'world memory must be persisted');
assert(game.includes('evolveRelicSite')&&game.includes('evolveOutpost'),'world evolution traces missing');
assert(game.includes('updateWorldEvolution')&&game.includes('evolution:0'),'world evolution state missing');
