/* Dungeon Echo i18n runtime follower v1.
 * Keeps dynamic DOM generated by legacy/late modules aligned with DE_I18N without moving
 * gameplay/state ownership out of game.js or input/audio modules.
 */
(() => {
  'use strict';
  if (typeof window==='undefined'||typeof document==='undefined'||window.__DE_I18N_RUNTIME_V1)return;
  const api=window.DE_TEST, L=window.DE_I18N;
  if(!api||!L)return;
  let applying=false;
  const setText=(el,value)=>{if(el&&el.textContent!==value)el.textContent=value};

  function classStats(c){
    if(!c)return '';
    return L.isEnglish
      ? `HP ${c.hpBase} · ATK ${c.atkBase} · Potions ${c.potions} · Scrolls ${c.scrolls}<br>Skill: ${c.skill.name} (CD ${c.skill.cd})<br>${c.skill.desc}`
      : `生命 ${c.hpBase} · 攻击 ${c.atkBase} · 药水 ${c.potions} · 卷轴 ${c.scrolls}<br>技能：${c.skill.name}（冷却 ${c.skill.cd}）<br>${c.skill.desc}`;
  }

  function syncClassCards(){
    const root=document.getElementById('class-grid');if(!root)return 0;
    let changed=0;
    for(const card of root.querySelectorAll('[data-class]')){
      const c=api.CLASSES&&api.CLASSES[card.dataset.class];if(!c)continue;
      const h=card.querySelector('h3'),p=card.querySelector('p'),s=card.querySelector('.stats');
      if(h&&h.textContent!==c.name){h.textContent=c.name;changed++}
      if(p&&p.textContent!==c.blurb){p.textContent=c.blurb;changed++}
      const html=classStats(c);if(s&&s.innerHTML!==html){s.innerHTML=html;changed++}
    }
    return changed;
  }

  function syncCurrentClass(){
    const el=document.getElementById('st-class');
    const id=api.classId||(api.meta&&api.meta.classId);
    const c=id&&api.CLASSES&&api.CLASSES[id];
    if(el&&c&&el.textContent!==c.name)el.textContent=c.name;
  }

  function setAction(act,key,hotkey){
    const el=document.querySelector(`#actions [data-act="${act}"]`);if(!el)return;
    const mobile=document.documentElement.classList.contains('de-mobile-ui');
    const label=L.t(key);
    if(mobile){setText(el,label);return;}
    let hk=el.querySelector('span');
    if(!hk){hk=document.createElement('span');el.appendChild(hk)}
    if(hk.textContent!==hotkey)hk.textContent=hotkey;
    let first=Array.from(el.childNodes).find(n=>n.nodeType===3);
    if(!first){first=document.createTextNode('');el.insertBefore(first,el.firstChild)}
    const wanted=label+' ';if(first.nodeValue!==wanted)first.nodeValue=wanted;
  }

  function syncLateControls(){
    setAction('attack','action.attack','J');setAction('skill','action.skill','K');setAction('potion','action.potion','Q');
    setAction('scroll','action.scroll','E');setAction('escape','action.escape','T');setAction('descend','action.descend','Enter');
    setAction('pause','action.pause','Esc');setAction('mute','action.sound','M');

    const greedy=document.getElementById('btn-greedy');
    if(greedy)setText(greedy,L.t(greedy.getAttribute('aria-pressed')==='true'?'title.greedy.on':'title.greedy.off'));

    const pop=document.getElementById('de-audio-settings-pop');
    if(pop){
      setText(pop.querySelector('.de-audio-head b'),L.t('audio.title'));
      const labels=pop.querySelectorAll('label span');setText(labels[0],L.t('audio.music'));setText(labels[1],L.t('audio.sfx'));
      setText(document.getElementById('de-audio-preset'),L.t('audio.preset'));
      setText(pop.querySelector('small'),L.t('audio.note'));
      setText(document.getElementById('de-audio-master'),window.__DE_AUDIO_DIRECTOR&&window.__DE_AUDIO_DIRECTOR.muted?L.t('audio.off'):L.t('audio.on'));
    }

    setText(document.querySelector('#help-screen .help-cols p'),L.t('mobile.help'));
    setText(document.getElementById('de-tutorial-reset'),L.t('tutorial.reset'));
    setText(document.querySelector('#de-onboarding b'),L.t('tutorial.label'));
    setText(document.querySelector('#de-onboarding [data-tutorial-skip]'),L.t('tutorial.skip'));
  }

  function syncCoreStatus(){
    const skill=document.getElementById('st-skill');
    const shop=document.getElementById('shop-gold');
    const warning=document.getElementById('guardian-break-warning');
    const feedback=document.getElementById('de-combat-feedback');
    if(L.isEnglish){
      if(skill){const raw=String(skill.textContent||'').trim();if(raw==='就绪')skill.textContent='Ready';else if(/^冷却\s*\d+/.test(raw))skill.textContent=raw.replace(/^冷却\s*/,'CD ')}
      if(shop&&/^金币\s*\d+/.test(shop.textContent||''))shop.textContent=shop.textContent.replace(/^金币/,'Gold');
      if(warning&&warning.textContent==='破甲大招 · 命中无视护甲')warning.textContent='Armor-break special · Hit ignores armor';
      if(feedback){const raw=String(feedback.textContent||'');if(/^蓝量不足：/.test(raw))feedback.textContent=raw.replace(/^蓝量不足：/,'Not enough mana: ').replace(' · 原地等待可更快恢复',' · Wait/focus to recover faster');else if(/^凝神 \+/.test(raw))feedback.textContent=raw.replace(/^凝神/,'Focus').replace(' 蓝量',' mana');else if(/ −\d+ 蓝量$/.test(raw))feedback.textContent=raw.replace(/ 蓝量$/,' mana')}
    }else{
      if(skill&&skill.textContent==='Ready')skill.textContent='就绪';
      if(shop&&/^Gold\s*\d+/.test(shop.textContent||''))shop.textContent=shop.textContent.replace(/^Gold/,'金币');
      if(warning&&warning.textContent==='Armor-break special · Hit ignores armor')warning.textContent='破甲大招 · 命中无视护甲';
    }
  }

  function sync(){
    if(applying)return;applying=true;
    try{syncClassCards();syncCurrentClass();syncLateControls();syncCoreStatus()}finally{applying=false}
  }

  const observer=typeof MutationObserver!=='undefined'?new MutationObserver(sync):null;
  if(observer&&document.body)observer.observe(document.body,{childList:true,subtree:true,characterData:true});
  window.addEventListener('de:languagechange',()=>requestAnimationFrame(sync));
  setInterval(sync,250);
  sync();
  window.__DE_I18N_RUNTIME_V1={version:'v1',sync,syncClassCards,syncCurrentClass,syncLateControls};
})();
