/* Dungeon Echo i18n runtime follower v1.
 * Keeps dynamic DOM generated by the legacy core aligned with DE_I18N without moving
 * gameplay/state ownership out of game.js.
 */
(() => {
  'use strict';
  if (typeof window==='undefined'||typeof document==='undefined'||window.__DE_I18N_RUNTIME_V1)return;
  const api=window.DE_TEST, L=window.DE_I18N;
  if(!api||!L)return;
  let applying=false;

  function classStats(c){
    if(!c)return '';
    return L.isEnglish
      ? `HP ${c.hpBase} · ATK ${c.atkBase} · Potions ${c.potions} · Scrolls ${c.scrolls}<br>Skill: ${c.skill.name} (CD ${c.skill.cd})<br>${c.skill.desc}`
      : `生命 ${c.hpBase} · 攻击 ${c.atkBase} · 药水 ${c.potions} · 卷轴 ${c.scrolls}<br>技能：${c.skill.name}（冷却 ${c.skill.cd}）<br>${c.skill.desc}`;
  }

  function syncClassCards(){
    const root=document.getElementById('class-grid');if(!root)return 0;
    let changed=0;
    for(const card of root.querySelectorAll('[data-class]')){
      const c=api.CLASSES&&api.CLASSES[card.dataset.class];if(!c)continue;
      const h=card.querySelector('h3'),p=card.querySelector('p'),s=card.querySelector('.stats');
      if(h&&h.textContent!==c.name){h.textContent=c.name;changed++}
      if(p&&p.textContent!==c.blurb){p.textContent=c.blurb;changed++}
      const html=classStats(c);if(s&&s.innerHTML!==html){s.innerHTML=html;changed++}
    }
    return changed;
  }

  function syncCurrentClass(){
    const el=document.getElementById('st-class');
    const id=api.classId||(api.meta&&api.meta.classId);
    const c=id&&api.CLASSES&&api.CLASSES[id];
    if(el&&c&&el.textContent!==c.name)el.textContent=c.name;
  }

  function syncCoreStatus(){
    if(!L.isEnglish)return;
    const skill=document.getElementById('st-skill');
    if(skill){
      const raw=String(skill.textContent||'').trim();
      if(raw==='就绪')skill.textContent='Ready';
      else if(/^冷却\s*\d+/.test(raw))skill.textContent=raw.replace(/^冷却\s*/,'CD ');
    }
    const shop=document.getElementById('shop-gold');
    if(shop&&/^金币\s*\d+/.test(shop.textContent||''))shop.textContent=shop.textContent.replace(/^金币/,'Gold');
    const warning=document.getElementById('guardian-break-warning');
    if(warning&&warning.textContent==='破甲大招 · 命中无视护甲')warning.textContent='Armor-break special · Hit ignores armor';
    const feedback=document.getElementById('de-combat-feedback');
    if(feedback){
      const raw=String(feedback.textContent||'');
      if(/^蓝量不足：/.test(raw))feedback.textContent=raw.replace(/^蓝量不足：/,'Not enough mana: ').replace(' · 原地等待可更快恢复',' · Wait/focus to recover faster');
      else if(/^凝神 \+/.test(raw))feedback.textContent=raw.replace(/^凝神/,'Focus').replace(' 蓝量',' mana');
      else if(/ −\d+ 蓝量$/.test(raw))feedback.textContent=raw.replace(/ 蓝量$/,' mana');
    }
  }

  function sync(){
    if(applying)return;applying=true;
    try{syncClassCards();syncCurrentClass();syncCoreStatus()}finally{applying=false}
  }

  const observer=typeof MutationObserver!=='undefined'?new MutationObserver(sync):null;
  if(observer&&document.body)observer.observe(document.body,{childList:true,subtree:true,characterData:true});
  window.addEventListener('de:languagechange',()=>requestAnimationFrame(sync));
  setInterval(sync,300);
  sync();
  window.__DE_I18N_RUNTIME_V1={version:'v1',sync,syncClassCards,syncCurrentClass};
})();
