(() => {
'use strict';
const $ = id => document.getElementById(id);
const canvas=$('game'), ctx=canvas.getContext('2d',{alpha:false}), frame=$('gameFrame');
const overlay=$('overlay'), startBtn=$('startBtn'), overlayTitle=$('overlayTitle'), overlayText=$('overlayText');
const scoreEl=$('score'), speedEl=$('speed'), comboEl=$('combo'), bestEl=$('best'), bestBelow=$('bestBelow'), bestComboEl=$('bestCombo'), runsEl=$('runs'), onTimeEndsEl=$('onTimeEnds'), overtimeEndsEl=$('overtimeEnds');
const clockEl=$('clock'), stageEl=$('stage'), sceneHud=$('sceneHud'), sceneToast=$('sceneToast'), tickerEl=$('ticker'), dayProgress=$('dayProgress'), fullscreenBtn=$('fullscreenBtn'), fullscreenLabel=$('fullscreenLabel'), bgmChip=$('bgmChip'), bgmHud=$('bgmHud'), eventChip=$('eventChip'), eventHud=$('eventHud'), tutorialToast=$('tutorialToast'), discoveryCountEl=$('discoveryCount'), discoveryListEl=$('discoveryList');
const messageBtn=$('messageBtn'),messageComposer=$('messageComposer'),messageName=$('messageName'),messageText=$('messageText'),messageCount=$('messageCount'),messageSubmit=$('messageSubmit'),messageStatus=$('messageStatus');
const settingsBtn=$('settingsBtn'), settingsPop=$('settingsPop'), masterSoundBtn=$('masterSoundBtn'), musicVolEl=$('musicVol'), sfxVolEl=$('sfxVol'), musicVolOut=$('musicVolOut'), sfxVolOut=$('sfxVolOut'), mixPresetBtn=$('mixPresetBtn'), langBtn=$('langBtn'), routeStrip=$('routeStrip');

const storageGet=key=>{try{return window.localStorage.getItem(key)}catch{return null}};
const storageSet=(key,value)=>{try{window.localStorage.setItem(key,String(value));return true}catch{return false}};
const storageRemove=key=>{try{window.localStorage.removeItem(key);return true}catch{return false}};
const storedNumber=(key,fallback=0)=>{const n=Number(storageGet(key));return Number.isFinite(n)?n:fallback};

const UI_I18N = {"brand":{"zh":"摸鱼到下班","en":"Clock Out Alive"},"brandMeta":{"zh":"91HWL · WEB TOY · 办公室逃班跑酷","en":"91HWL · WEB TOY · OFFICE ESCAPE RUNNER"},"home":{"zh":"← 91hwl 首页","en":"← 91hwl Home"},"settings":{"zh":"设置","en":"Settings"},"audioSettings":{"zh":"声音设置","en":"Audio"},"music":{"zh":"背景音乐","en":"Music"},"sfx":{"zh":"游戏音效","en":"SFX"},"mixPreset":{"zh":"恢复推荐 30 / 85","en":"Recommended 30 / 85"},"mixNote":{"zh":"当前推荐混音：音乐 30%，音效 85%。两者独立保存；按 M 可快速静音/恢复。","en":"Recommended mix: music 30%, SFX 85%. Saved separately. Press M to mute or restore."},"fullscreen":{"zh":"全屏","en":"Fullscreen"},"score":{"zh":"摸鱼","en":"Escape"},"speed":{"zh":"速度","en":"Speed"},"combo":{"zh":"连摸","en":"Combo"},"event":{"zh":"事件","en":"Event"},"scene":{"zh":"场景","en":"Scene"},"best":{"zh":"最高","en":"Best"},"heroTitle":{"zh":"别让老板逮到。","en":"Don't let the boss catch you."},"heroText":{"zh":"从 14:00 撑到 18:00。穿过工位区、会议室、茶水间和员工健身房，躲开工作，喝点咖啡，尽量活着看到下班。声音默认关闭，可在右上角开启原创 8-bit / Chiptune BGM。","en":"Survive the office from 14:00 to 18:00. Sprint through workstations, meetings, the pantry and the gym. Dodge work, grab coffee and reach the exit. Original 8-bit / Chiptune audio is off by default."},"start":{"zh":"开始摸鱼","en":"Start escaping"},"leaveMessage":{"zh":"写一句话","en":"Leave a note"},"controls":{"zh":"电脑：空格 / ↑ / 鼠标点击跳跃，空中可二段跳 · P / Esc 暂停 · M 快速静音<br>手机：轻触游戏画面。首次游玩会有两步无打断教学。18:00 会出现短暂「下班窗口」：及时操作可准点下班，否则将被判定为“自愿”加班。","en":"Desktop: Space / ↑ / click to jump; press again in mid-air for a double jump · P / Esc pause · M mute<br>Mobile: tap the game. First run includes a two-step tutorial. At 18:00, react during the short clock-out window—or be marked as “voluntary” overtime."},"localStats":{"zh":"本机战绩","en":"Local record"},"bestRun":{"zh":"最高摸鱼","en":"Best run"},"bestCombo":{"zh":"最佳连摸","en":"Best combo"},"runs":{"zh":"摸鱼次数","en":"Runs"},"onTime":{"zh":"准点下班","en":"On-time exits"},"overtime":{"zh":"“自愿”加班","en":"“Voluntary” OT"},"discoveries":{"zh":"发现档案","en":"Discovery file"},"discoveryNote":{"zh":"发现记录只保存在当前浏览器；未发现项目只显示为 ???。","en":"Discoveries stay in this browser. Locked entries remain ???."},"route0":{"zh":"工位区 · Workstation","en":"Workstation · survive"},"route1":{"zh":"会议室 · Meeting","en":"Meeting · slip out"},"route2":{"zh":"茶水间 · Pantry","en":"Pantry · refuel"},"route3":{"zh":"健身房 · Gym","en":"Gym · final sprint"},"route4":{"zh":"下班门 · Clock out","en":"Exit · clock out"},"messageModeration":{"zh":"提交后需审核 · 不即时公开","en":"Moderated · not published instantly"}};
