#!/usr/bin/env bash
set -euo pipefail
BUNDLE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SITE_ROOT=/srv/91hwl-play; RELEASES_DIR=$SITE_ROOT/releases; CURRENT_LINK=$SITE_ROOT/current; SOURCE=$BUNDLE_ROOT/public/moyu; HEALTHCHECK=$BUNDLE_ROOT/ops/healthcheck.sh
fail(){ echo "MOYU_SITE_DEPLOY_ERROR: $*" >&2; exit 1; }
test "${EUID:-$(id -u)}" -eq 0 || fail 'root required'; test "$#" -eq 0 || fail 'this deployer accepts no arguments'
for f in "$SOURCE/index.html" "$SOURCE/style.css" "$SOURCE/visual-v1113.css" "$SOURCE/responsive-v1120.css" "$SOURCE/game.js" "$SOURCE/VERSION" "$BUNDLE_ROOT/VERSION" "$BUNDLE_ROOT/REVISION" "$BUNDLE_ROOT/SHA256SUMS"; do test -r "$f" || fail "missing $f"; done
test -x "$HEALTHCHECK" || fail 'bundle healthcheck missing'; (cd "$BUNDLE_ROOT" && sha256sum --check --status SHA256SUMS) || fail 'bundle checksum verification failed'
previous_release="$(readlink -f "$CURRENT_LINK")"; [[ "$previous_release" == "$RELEASES_DIR"/* ]] || fail 'existing 91hwl-play current release is invalid'; test -r "$previous_release/dungeon-echo/index.html" || fail 'existing Dungeon Echo release is missing'
revision="$(tr -d '\r\n' < "$BUNDLE_ROOT/REVISION")"; version="$(tr -d '\r\n' < "$BUNDLE_ROOT/VERSION")"; test "$version" = '1.12.0' || fail "unexpected Moyu version: $version"; test "$(tr -d '\r\n' < "$SOURCE/VERSION")" = "$version" || fail 'Moyu VERSION mismatch'
grep -Fq '<meta name="version" content="1.12.0"' "$SOURCE/index.html" || fail 'release marker missing'; grep -Fq 'style.css?v=1120' "$SOURCE/index.html" || fail 'base CSS fingerprint missing'; grep -Fq 'visual-v1113.css?v=1120' "$SOURCE/index.html" || fail 'visual CSS fingerprint missing'; grep -Fq 'responsive-v1120.css?v=1120' "$SOURCE/index.html" || fail 'responsive CSS fingerprint missing'; grep -Fq 'game.js?v=1120' "$SOURCE/index.html" || fail 'JS fingerprint missing'; grep -Fq 'translate="no"' "$SOURCE/index.html" || fail 'browser translation suppression missing'; grep -Fq "(cl==='zh'||cl==='en')?cl:((sl==='zh'||sl==='en')?sl:bl)" "$SOURCE/index.html" || fail 'validated prepaint precedence missing'; ! grep -Fq "c('91hwl_lang')||localStorage.getItem('91hwl_lang')||" "$SOURCE/index.html" || fail 'legacy prepaint precedence remains'
grep -Fq "dataset.gameVersion='1.12.0'" "$SOURCE/game.js" || fail 'runtime marker missing'; grep -Fq 'groundTakeoff=before===0' "$SOURCE/game.js" || fail 'ground-only jump dust guard missing'; grep -Fq 'writeSharedLangCookie(currentLang)' "$SOURCE/game.js" || fail 'shared language bridge missing'; grep -Fq 'const storedLang=storageGet(LANG_KEY)' "$SOURCE/game.js" || fail 'stored language validation missing'; grep -Fq "(storedLang==='en'||storedLang==='zh')?storedLang:browserLang" "$SOURCE/game.js" || fail 'stored language fallback missing'; ! grep -Fq "storageGet(LANG_KEY)||(navigator.language||'zh').toLowerCase().startsWith('zh')?'zh':'en'" "$SOURCE/game.js" || fail 'ambiguous language precedence remains'; grep -Fq 'repeatSensitiveKeys' "$SOURCE/game.js" || fail 'repeat-input guard missing'; grep -Fq 'canvasLayoutDirty' "$SOURCE/game.js" || fail 'canvas resize guard missing'; grep -Fq 'syncPresentationState.signature' "$SOURCE/game.js" || fail 'presentation memoization missing'; grep -Fq 'function viewportFrameMaxWidth' "$SOURCE/game.js" || fail 'viewport frame calculator missing'; grep -Fq 'function fitGameFrameToViewport' "$SOURCE/game.js" || fail 'viewport-first frame fitting missing'; grep -Fq 'effectiveSpawnWidth(spawned)' "$SOURCE/game.js" || fail 'spawn width reserve missing'; ! grep -Fq 'drawPlayerFocus(drawX,footY,altitude);' "$SOURCE/game.js" || fail 'player focus halo still active'; ! grep -Fq 'drawBackground();drawAmbientOfficeLife();drawRunAtmosphere();' "$SOURCE/game.js" || fail 'drifting ambient coworkers still active'; grep -Fq 'font-size:17px' "$SOURCE/visual-v1113.css" || fail 'result body typography missing'; grep -Fq 'font-size:14.5px' "$SOURCE/visual-v1113.css" || fail 'result control typography missing'; grep -Fq 'height:44px' "$SOURCE/visual-v1113.css" || fail 'top control scale missing'; grep -Fq 'env(safe-area-inset-bottom)' "$SOURCE/responsive-v1120.css" || fail 'mobile safe-area rule missing'; grep -Fq '.home-link::before' "$SOURCE/responsive-v1120.css" || fail 'narrow header compaction missing'; grep -Fq '@media(max-width:700px) and (orientation:portrait)' "$SOURCE/responsive-v1120.css" || fail 'portrait viewport rule missing'; grep -Fq 'padding-left:max(2px,env(safe-area-inset-left))' "$SOURCE/responsive-v1120.css" || fail 'portrait width expansion missing'
release_name="$(date -u +%Y%m%dT%H%M%SZ)-moyu-${revision:0:12}"; release_dir="$RELEASES_DIR/$release_name"; tmp_dir="$(mktemp -d "$RELEASES_DIR/.moyu-${revision:0:12}.XXXXXX")"; next_link="$SITE_ROOT/.current-moyu-${revision:0:12}"; switched=false
rollback(){ rc=$?; if test "$rc" -ne 0; then if test "$switched" = true; then r="$SITE_ROOT/.rollback-moyu-${revision:0:12}"; ln -s "$previous_release" "$r"; mv -Tf "$r" "$CURRENT_LINK"; systemctl reload nginx >/dev/null 2>&1 || true; fi; rm -rf -- "$tmp_dir"; rm -f -- "$next_link"; echo 'moyu_site_deploy=ROLLED_BACK' >&2; fi; exit "$rc"; }
trap rollback EXIT
cp -aL "$previous_release/." "$tmp_dir/"; rm -rf -- "$tmp_dir/moyu"; mkdir -p "$tmp_dir/moyu"; cp -a "$SOURCE/." "$tmp_dir/moyu/"; test -r "$tmp_dir/dungeon-echo/index.html" || fail 'Dungeon Echo was not preserved'; find "$tmp_dir" -type d -exec chmod 0755 {} +; find "$tmp_dir" -type f -exec chmod 0644 {} +
mv "$tmp_dir" "$release_dir"; ln -s "$release_dir" "$next_link"; mv -Tf "$next_link" "$CURRENT_LINK"; switched=true; nginx -t; systemctl reload nginx; "$HEALTHCHECK"; trap - EXIT
echo "site_release=$release_dir"; echo "moyu_revision=$revision"; echo "moyu_version=$version"; echo 'moyu_site_deploy=PASS'
