#!/usr/bin/env bash
set -euo pipefail
BUNDLE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; GAME_URL=https://play.91hwl.cn/moyu/; VERSION_URL=https://play.91hwl.cn/moyu/VERSION; ORIGIN=play.91hwl.cn:443:127.0.0.1
fail(){ echo "MOYU_HEALTHCHECK_ERROR: $*" >&2; exit 1; }
version="$(tr -d '\r\n' < "$BUNDLE_ROOT/VERSION")"; revision="$(tr -d '\r\n' < "$BUNDLE_ROOT/REVISION")"; work="$(mktemp -d /tmp/moyu-health.XXXXXX)"; trap 'rm -rf -- "$work"' EXIT
probe(){ prefix="$1"; shift; curl -fsSL --noproxy '*' "$@" -o "$work/$prefix.html"; grep -Fq '<meta name="version" content="1.12.0"' "$work/$prefix.html"; grep -Fq 'style.css?v=1120' "$work/$prefix.html"; grep -Fq 'visual-v1113.css?v=1120' "$work/$prefix.html"; grep -Fq 'responsive-v1120.css?v=1120' "$work/$prefix.html"; grep -Fq 'game.js?v=1120' "$work/$prefix.html"; grep -Fq 'translate="no"' "$work/$prefix.html"; grep -Fq "(cl==='zh'||cl==='en')?cl:((sl==='zh'||sl==='en')?sl:bl)" "$work/$prefix.html"; ! grep -Fq "c('91hwl_lang')||localStorage.getItem('91hwl_lang')||" "$work/$prefix.html"; }
probe origin --resolve "$ORIGIN" "$GAME_URL" || fail 'origin HTML/prepaint check failed'
curl -fsSL --noproxy '*' --resolve "$ORIGIN" "https://play.91hwl.cn/moyu/visual-v1113.css?v=1120" -o "$work/visual.css" || fail 'origin visual CSS missing'; grep -Fq 'font-size:17px' "$work/visual.css" || fail 'result body readability rule missing'; grep -Fq 'font-size:14.5px' "$work/visual.css" || fail 'result control readability rule missing'; grep -Fq 'height:44px' "$work/visual.css" || fail 'top control scale missing'
curl -fsSL --noproxy '*' --resolve "$ORIGIN" "https://play.91hwl.cn/moyu/responsive-v1120.css?v=1120" -o "$work/responsive.css" || fail 'origin responsive CSS missing'; grep -Fq 'env(safe-area-inset-bottom)' "$work/responsive.css" || fail 'mobile safe-area rule missing'; grep -Fq '@media(max-width:560px)' "$work/responsive.css" || fail 'narrow phone breakpoint missing'; grep -Fq '.home-link::before' "$work/responsive.css" || fail 'narrow header compaction missing'; grep -Fq '@media(max-width:700px) and (orientation:portrait)' "$work/responsive.css" || fail 'portrait viewport rule missing'; grep -Fq 'padding-left:max(2px,env(safe-area-inset-left))' "$work/responsive.css" || fail 'portrait width expansion missing'
curl -fsSL --noproxy '*' --resolve "$ORIGIN" "https://play.91hwl.cn/moyu/game.js?v=1120" -o "$work/game.js" || fail 'origin JS missing'; grep -Fq "dataset.gameVersion='1.12.0'" "$work/game.js" || fail 'runtime version mismatch'; grep -Fq 'groundTakeoff=before===0' "$work/game.js" || fail 'ground-only jump dust guard missing'; grep -Fq 'writeSharedLangCookie(currentLang)' "$work/game.js" || fail 'shared language bridge missing'; grep -Fq 'const storedLang=storageGet(LANG_KEY)' "$work/game.js" || fail 'stored language validation missing'; grep -Fq "(storedLang==='en'||storedLang==='zh')?storedLang:browserLang" "$work/game.js" || fail 'stored language fallback missing'; ! grep -Fq "storageGet(LANG_KEY)||(navigator.language||'zh').toLowerCase().startsWith('zh')?'zh':'en'" "$work/game.js" || fail 'ambiguous language precedence remains'; grep -Fq 'repeatSensitiveKeys' "$work/game.js" || fail 'repeat-input guard missing'; grep -Fq 'canvasLayoutDirty' "$work/game.js" || fail 'canvas layout guard missing'; grep -Fq 'syncPresentationState.signature' "$work/game.js" || fail 'presentation memoization missing'; grep -Fq 'function viewportFrameMaxWidth' "$work/game.js" || fail 'viewport frame calculator missing'; grep -Fq 'function fitGameFrameToViewport' "$work/game.js" || fail 'viewport-first frame fitting missing'; grep -Fq 'effectiveSpawnWidth(spawned)' "$work/game.js" || fail 'long BUG gap reserve missing'; ! grep -Fq 'drawPlayerFocus(drawX,footY,altitude);' "$work/game.js" || fail 'player halo still active'; ! grep -Fq 'drawBackground();drawAmbientOfficeLife();drawRunAtmosphere();' "$work/game.js" || fail 'drifting ambient coworkers still active'
actual="$(curl -fsSL --noproxy '*' --resolve "$ORIGIN" "$VERSION_URL" | tr -d '\r\n[:space:]')"; test "$actual" = "$version" || fail 'origin VERSION mismatch'
# Both explicit language routes must keep the same validated prepaint selector and v1.12.0 assets.
for lang in zh en; do curl -fsSL --noproxy '*' --resolve "$ORIGIN" "${GAME_URL}?lang=$lang&release=$revision" -o "$work/$lang.html" || fail "origin $lang route failed"; grep -Fq 'game.js?v=1120' "$work/$lang.html" || fail "$lang route asset mismatch"; grep -Fq 'responsive-v1120.css?v=1120' "$work/$lang.html" || fail "$lang responsive asset mismatch"; grep -Fq "(cl==='zh'||cl==='en')?cl:((sl==='zh'||sl==='en')?sl:bl)" "$work/$lang.html" || fail "$lang validated prepaint selector missing"; done
public_ok=false; for i in 1 2 3 4 5 6; do if probe public "${GAME_URL}?release=$revision" && test "$(curl -fsSL "${VERSION_URL}?release=$revision" | tr -d '\r\n[:space:]')" = "$version"; then public_ok=true; break; fi; sleep 2; done; test "$public_ok" = true || fail 'public Moyu check failed'
curl -fsSL --noproxy '*' --resolve "$ORIGIN" https://play.91hwl.cn/dungeon-echo/ -o /dev/null || fail 'Dungeon Echo preservation check failed'
echo "public_url=$GAME_URL"; echo "public_version=$version"; echo 'moyu_healthcheck=PASS'
