#!/usr/bin/env bash
set -euo pipefail
BUNDLE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; SITE_ROOT=/var/www/91hwl; BACKUP_ROOT=/var/backups/91hwl-home-mount; PUBLIC=$BUNDLE_ROOT/public; HEALTH=$BUNDLE_ROOT/ops/healthcheck.sh
fail(){ echo "WEB_TOYS_HOME_MOUNT_ERROR: $*" >&2; exit 1; }
test "${EUID:-$(id -u)}" -eq 0||fail 'root required'; test "$#" -eq 0||fail 'no arguments'; (cd "$BUNDLE_ROOT"&&sha256sum --check --status SHA256SUMS)||fail 'bundle checksum failed'; test "$(cat "$BUNDLE_ROOT/VERSION"|tr -d '\r\n')" = '1.3.1'||fail 'unexpected site version'
for f in "$PUBLIC/index.html" "$PUBLIC/toys/dungeon-echo/index.html" "$PUBLIC/toys/moyu/index.html";do test -r "$f"||fail "missing $f";done
grep -Fq 'data-site-version="1.3.1"' "$PUBLIC/index.html"||fail 'home marker missing'; grep -Fq 'softwareVersion":"1.2.6"' "$PUBLIC/toys/dungeon-echo/index.html"||fail 'Dungeon detail marker missing'; grep -Fq 'softwareVersion":"1.11.1"' "$PUBLIC/toys/moyu/index.html"||fail 'Moyu detail marker missing'
expected="$(cat "$BUNDLE_ROOT/EXPECTED_INDEX_SHA256"|tr -d '\r\n')"; actual="$(sha256sum "$SITE_ROOT/index.html"|awk '{print $1}')"; new="$(sha256sum "$PUBLIC/index.html"|awk '{print $1}')"; if test "$actual" != "$expected" && test "$actual" != "$new";then fail "live homepage changed unexpectedly: $actual";fi
mkdir -p "$BACKUP_ROOT"; backup="$(mktemp -d "$BACKUP_ROOT/web-toys-v131.XXXXXX")"; cp -a "$SITE_ROOT/index.html" "$backup/index.html"; cp -a "$SITE_ROOT/toys" "$backup/toys" 2>/dev/null||true
rollback(){ rc=$?; if test "$rc" -ne 0;then cp -a "$backup/index.html" "$SITE_ROOT/index.html"; rm -rf "$SITE_ROOT/toys"; test -e "$backup/toys"&&cp -a "$backup/toys" "$SITE_ROOT/toys"; nginx -t>/dev/null 2>&1&&systemctl reload nginx>/dev/null 2>&1||true; echo 'web_toys_home_mount=ROLLED_BACK' >&2;fi;exit "$rc";};trap rollback EXIT
install -m0644 "$PUBLIC/index.html" "$SITE_ROOT/.index.v131.tmp";chown --reference="$SITE_ROOT/index.html" "$SITE_ROOT/.index.v131.tmp";mv -Tf "$SITE_ROOT/.index.v131.tmp" "$SITE_ROOT/index.html";mkdir -p "$SITE_ROOT/toys/dungeon-echo" "$SITE_ROOT/toys/moyu";install -m0644 "$PUBLIC/toys/dungeon-echo/index.html" "$SITE_ROOT/toys/dungeon-echo/index.html";install -m0644 "$PUBLIC/toys/moyu/index.html" "$SITE_ROOT/toys/moyu/index.html"
nginx -t;systemctl reload nginx;"$HEALTH";trap - EXIT;echo "backup_dir=$backup";echo 'web_toys_home_mount=PASS'
