/* classic-30 内容 Profile（schemaVersion 2）
 * 1–20 层沿用加深线；21–30 为熔岩锻炉 / 蛛丝墓穴 / 星骸神殿。
 * 第 10 / 20 层中层 Boss 可继续下潜；第 30 层终局，可选择无尽回响。
 */
window.DE_PROFILES = window.DE_PROFILES || {};
window.DE_PROFILES['classic-30'] = {
  schemaVersion: 2,
  profileId: 'classic-30',
  title: '回响无尽 · 三十层',

  floorRules: {
    maxDepth: 30,
    themeBandSize: 3,
    baseMonsterCount: 5,
    monsterPerDepth: 1,
    maxMonsters: 14,
    eliteChance: 0.13,
    eliteHpMult: 1.85,
    eliteAtkMult: 1.25,
    depthScaleMax: 0.32,
    lootChances: { scroll: 0.45, equip1: 0.52, equip2: 0.34 },
    killLoot: { gold: 0.60, potion: 0.74, equip: 0.83 },
    lootCounts: {
      potionLo: 1, potionHi: 2,
      goldLo: 3, goldHi: 5,
      floorGoldLo: 6, floorGoldHi: 16, floorGoldPerDepth: 3,
      killGoldLo: 4, killGoldHi: 12, killGoldPerDepth: 2,
    },
    minMonsters: 5,
    minPotions: 2,
    minGoldPiles: 2,
    minEquips: 1,
    shrineChance: 0.34,
    trapCountLo: 1,
    trapCountHi: 4,
    secretChance: 0.55,
    endlessAfter: true,
  },

  consumables: {
    potion: { icon: 'healing-potion', name: '治疗药水' },
    scroll: { icon: 'teleport-scroll', name: '传送卷轴' },
    gold:   { icon: 'gold-pile', name: '金币' },
    key:    { icon: 'dungeon-key', name: '锈蚀钥匙' },
  },

  themes: [
    { name: '石砌地窟', fl: '#262c38', fl2: '#222734', sp1: '#1c212c', sp2: '#2f3644', wa: '#3d4356', wl: '#262b38', wh: 'rgba(255,255,255,.08)' },
    { name: '苔湿洞穴', fl: '#243026', fl2: '#202a23', sp1: '#182018', sp2: '#2d3b2d', wa: '#3a4a3c', wl: '#232e24', wh: 'rgba(220,255,220,.07)' },
    { name: '血色深渊', fl: '#33232a', fl2: '#2d1f26', sp1: '#22161c', sp2: '#3d2b33', wa: '#4a3038', wl: '#301e24', wh: 'rgba(255,220,220,.07)' },
    { name: '地狱核心', fl: '#301c22', fl2: '#2a181e', sp1: '#1e1216', sp2: '#3a232b', wa: '#452a30', wl: '#2c1a1f', wh: 'rgba(255,200,160,.08)' },
    { name: '霜骨墓园', fl: '#1c2834', fl2: '#182430', sp1: '#121c26', sp2: '#2a3a48', wa: '#3a4e5e', wl: '#1e2c38', wh: 'rgba(180,220,255,.08)' },
    { name: '沉没圣堂', fl: '#1e2c2c', fl2: '#1a2626', sp1: '#121c1c', sp2: '#2c3e3a', wa: '#3a524c', wl: '#1c2c28', wh: 'rgba(180,230,210,.08)' },
    { name: '虚空裂隙', fl: '#1a1624', fl2: '#16121e', sp1: '#100e18', sp2: '#2a2438', wa: '#3a3450', wl: '#1e1a2c', wh: 'rgba(200,190,255,.08)' },
    { name: '熔岩锻炉', fl: '#3a2218', fl2: '#321c14', sp1: '#24140e', sp2: '#4a2c1c', wa: '#5a3824', wl: '#2e1a12', wh: 'rgba(255,160,80,.10)' },
    { name: '蛛丝墓穴', fl: '#2a2430', fl2: '#241e2a', sp1: '#18141e', sp2: '#3a3244', wa: '#4a4258', wl: '#2a2434', wh: 'rgba(220,200,255,.08)' },
    { name: '星骸神殿', fl: '#1c2438', fl2: '#182030', sp1: '#101828', sp2: '#2c3850', wa: '#3a4a68', wl: '#1c283c', wh: 'rgba(160,200,255,.10)' },
  ],

  monsters: [
    { sprite: 'rat',         name: '巨鼠',     color: '#b58900', hp: 4,  atk: 2,  def: 0, xp: 2,  min: 1, max: 4 },
    { sprite: 'bat',         name: '蝙蝠',     color: '#93a1a1', hp: 5,  atk: 2,  def: 0, xp: 3,  min: 1, max: 6, erratic: true },
    { sprite: 'goblin',      name: '哥布林',   color: '#859900', hp: 9,  atk: 4,  def: 1, xp: 6,  min: 2, max: 8 },
    { sprite: 'spider',      name: '墓穴蛛',   color: '#8a6a9a', hp: 10, atk: 5,  def: 1, xp: 7,  min: 3, max: 9, poison: true },
    { sprite: 'skeleton',    name: '骷髅',     color: '#eee8d5', hp: 13, atk: 5,  def: 2, xp: 9,  min: 4, max: 13 },
    { sprite: 'orc',         name: '兽人',     color: '#cb4b16', hp: 17, atk: 7,  def: 2, xp: 13, min: 6, max: 15 },
    { sprite: 'ghost',       name: '幽魂',     color: '#6c71c4', hp: 15, atk: 8,  def: 3, xp: 16, min: 7, max: 17 },
    { sprite: 'cultist',     name: '血教徒',   color: '#a05070', hp: 18, atk: 9,  def: 2, xp: 18, min: 8, max: 18 },
    { sprite: 'troll',       name: '巨魔',     color: '#2aa198', hp: 26, atk: 10, def: 3, xp: 24, min: 10, max: 18 },
    { sprite: 'demon',       name: '深渊恶魔', color: '#dc322f', hp: 36, atk: 12, def: 4, xp: 38, min: 12, max: 20, boom: true },
    { sprite: 'wraith',      name: '霜怨灵',   color: '#7ec8e3', hp: 28, atk: 11, def: 2, xp: 28, min: 13, max: 21, poison: true, regen: true },
    { sprite: 'frostmage',   name: '霜语法师', color: '#7eb8e8', hp: 24, atk: 13, def: 2, xp: 30, min: 14, max: 22, ranged: 3 },
    { sprite: 'golem',       name: '墓石魔像', color: '#8a94a8', hp: 42, atk: 13, def: 6, xp: 36, min: 16, max: 24, slow: true },
    { sprite: 'vampire',     name: '血爵',     color: '#c8452c', hp: 36, atk: 14, def: 4, xp: 42, min: 17, max: 25, leech: 0.25 },
    { sprite: 'lich',        name: '墓园巫妖', color: '#bc8ee9', hp: 34, atk: 15, def: 3, xp: 48, min: 19, max: 27, ranged: 2, enrage: true },
    { sprite: 'abomination', name: '缝合憎恶', color: '#6a8a4a', hp: 52, atk: 16, def: 5, xp: 52, min: 20, max: 28, slow: true, regen: true },
    { sprite: 'dragonkin',   name: '裂隙龙裔', color: '#e0a73f', hp: 48, atk: 19, def: 5, xp: 60, min: 22, max: 29, boom: true },
    { sprite: 'seraph',      name: '陨星使',   color: '#e8d8a0', hp: 44, atk: 20, def: 4, xp: 70, min: 24, max: 30, ranged: 2 },
    { sprite: 'voidspawn',   name: '虚空幼体', color: '#8b7ec8', hp: 42, atk: 20, def: 3, xp: 64, min: 26, max: 30, erratic: true, enrage: true },
  ],

  midBoss: { sprite: 'boss', name: '深渊领主', color: '#dc322f', hp: 120, atk: 15, def: 5, xp: 160, depth: 10 },
  midBosses: [
    { sprite: 'boss', name: '深渊领主', color: '#dc322f', hp: 120, atk: 15, def: 5, xp: 160, depth: 10 },
    { sprite: 'golem', name: '霜骨暴君', color: '#7ec8e3', hp: 180, atk: 18, def: 8, xp: 240, depth: 20 },
  ],
  boss: { sprite: 'voidlord', name: '虚空君王', color: '#8b7ec8', hp: 280, atk: 24, def: 9, xp: 420 },

  shopFloors: [4, 8, 12, 16, 22, 26],
  restFloors: [5, 15, 25],
  chestChance: 0.62,
  keyChance: 0.28,

  rarities: [
    { name: '普通', color: '#c9d4e3', affixes: 0, w: 50 },
    { name: '精良', color: '#7dd87d', affixes: 1, w: 27 },
    { name: '稀有', color: '#5aa7e8', affixes: 2, w: 14 },
    { name: '史诗', color: '#b07de8', affixes: 3, w: 7 },
    { name: '传说', color: '#eda23a', affixes: 4, w: 2 },
  ],
  weaponBases: [
    { name: '铁剑',     icon: 'iron-sword', atk: 2, min: 1, cls: 'warrior' },
    { name: '阔剑',     icon: 'broad-sword', atk: 4, min: 3, cls: 'warrior' },
    { name: '战斧',     icon: 'battle-axe', atk: 6, min: 5, cls: 'warrior' },
    { name: '符文之刃', icon: 'rune-blade', atk: 9, min: 7, cls: 'warrior' },
    { name: '骑士阔剑', icon: 'broad-sword', atk: 10, min: 10, cls: 'warrior' },
    { name: '裂隙之刃', icon: 'rune-blade', atk: 12, min: 14, cls: 'warrior' },
    { name: '碎甲战斧', icon: 'battle-axe', atk: 13, min: 17, cls: 'warrior' },
    { name: '星骸之刃', icon: 'rune-blade', atk: 16, min: 22, cls: 'warrior' },
    { name: '猎弓',     icon: 'hunting-bow', atk: 2, min: 1, cls: 'ranger' },
    { name: '强弓',     icon: 'hunting-bow', atk: 4, min: 3, cls: 'ranger' },
    { name: '鹰眼长弓', icon: 'hunting-bow', atk: 6, min: 5, cls: 'ranger' },
    { name: '追猎之弓', icon: 'hunting-bow', atk: 9, min: 7, cls: 'ranger' },
    { name: '猎手长弓', icon: 'hunting-bow', atk: 10, min: 10, cls: 'ranger' },
    { name: '裂空之弓', icon: 'hunting-bow', atk: 12, min: 14, cls: 'ranger' },
    { name: '幻影猎弓', icon: 'hunting-bow', atk: 13, min: 17, cls: 'ranger' },
    { name: '星辰猎弓', icon: 'hunting-bow', atk: 16, min: 22, cls: 'ranger' },
    { name: '学徒法杖', icon: 'arcane-staff', atk: 2, min: 1, cls: 'mage' },
    { name: '秘纹法杖', icon: 'arcane-staff', atk: 4, min: 3, cls: 'mage' },
    { name: '星光法杖', icon: 'arcane-staff', atk: 6, min: 5, cls: 'mage' },
    { name: '奥术权杖', icon: 'arcane-staff', atk: 9, min: 7, cls: 'mage' },
    { name: '贤者法杖', icon: 'arcane-staff', atk: 10, min: 10, cls: 'mage' },
    { name: '虚空法杖', icon: 'arcane-staff', atk: 12, min: 14, cls: 'mage' },
    { name: '星辉法杖', icon: 'arcane-staff', atk: 13, min: 17, cls: 'mage' },
    { name: '星骸法杖', icon: 'arcane-staff', atk: 16, min: 22, cls: 'mage' },
    { name: '匕首',     icon: 'dagger', atk: 2, min: 1, cls: 'assassin' },
    { name: '淬毒匕首', icon: 'dagger', atk: 4, min: 3, cls: 'assassin' },
    { name: '暗影匕首', icon: 'dagger', atk: 6, min: 5, cls: 'assassin' },
    { name: '夜刃',     icon: 'dagger', atk: 9, min: 7, cls: 'assassin' },
    { name: '双刃匕首', icon: 'dagger', atk: 10, min: 10, cls: 'assassin' },
    { name: '裂魂匕首', icon: 'dagger', atk: 12, min: 14, cls: 'assassin' },
    { name: '血牙匕首', icon: 'dagger', atk: 13, min: 17, cls: 'assassin' },
    { name: '星骸夜刃', icon: 'dagger', atk: 16, min: 22, cls: 'assassin' },
  ],
  armorBases: [
    { name: '皮甲',   icon: 'leather-armor', def: 1, min: 1 },
    { name: '锁子甲', icon: 'chain-mail', def: 2, min: 3 },
    { name: '板甲',   icon: 'plate-armor', def: 5, min: 5 },
    { name: '秘银铠', icon: 'mithril-armor', def: 7, min: 7 },
    { name: '虚空甲', icon: 'mithril-armor', def: 10, min: 14 },
    { name: '星骸甲', icon: 'mithril-armor', def: 13, min: 22 },
  ],
  ringBases: [
    { name: '铜戒指',   icon: 'copper-ring', hp: 5,  min: 1 },
    { name: '红宝石戒', icon: 'ruby-ring', hp: 10, min: 3 },
    { name: '守护之戒', icon: 'guardian-ring', hp: 16, min: 6 },
    { name: '永夜之戒', icon: 'guardian-ring', hp: 24, min: 13 },
    { name: '星骸之戒', icon: 'guardian-ring', hp: 32, min: 21 },
  ],
  affixRanges: {
    thorns:{ lo: 1, hiGrow: 1, growDiv: 4 },
    regen: { lo: 2, hiGrow: 3, growDiv: 4 },
    atk:   { lo: 1, hiGrow: 2, growDiv: 3 },
    def:   { lo: 1, hiGrow: 2, growDiv: 3 },
    hp:    { lo: 4, hi: 8, flatPerDepth: 1 },
    crit:  { lo: 2, hi: 6 },
    leech: { lo: 3, hi: 9 },
    gold:  { lo: 10, hi: 28 },
  },

  terminalReward: {
    kind: 'amulet',
    icon: 'dungeon-heart',
    name: '地牢之心',
    bossGoldBase: 280,
    bossGoldPerDepth: 14,
  },

  shop: {
    potionPrice: 16,
    scrollPrice: 28,
    keyPrice: 22,
    healPrice: 24,
    equipMult: 3,
  },

  texts: {
    intro: '三十层石窟在脚下展开。选一条回响，杀穿 {maxDepth} 层，从 {boss} 手中夺回「{heart}」——或踏入无尽。',
    bossGate: '{boss}封锁了最后的阶梯。击败它，夺回「{heart}」！',
    bossFloorArrive: '星骸在头顶碎裂……{boss}就在这一层！',
    maxDepthArrive: '你踏入了第 {maxDepth} 层——世界在这里被掏空，只剩回响。',
    bossDeath: '{boss}倒下了！它守护的【{heart}】掉落了出来！',
    winBody: '你取得了<b>{heart}</b>，三十层地牢在身后轰然崩塌！<br>',
    midBossArrive: '第 {depth} 层的门后，{midBoss}挡住了去路。击败它仍可继续下潜。',
    midBossDeath: '{midBoss}崩解了。通往更深处的阶梯重新亮起。',
    shopArrive: '一位蒙面商人在火把下摆开摊位。金币能换来活路。',
    restArrive: '一处余烬营地。你可以在此包扎伤口。',
    shrineArrive: '一座无名神龛在黑暗中发着微光。触碰它，接受回响的赌注。',
    endlessArrive: '你拒绝了归途。回响一层层叠上来——没有尽头，只有更深。',
    floorClear: '本层已肃清。阶梯处金光大盛，你感到一笔清场赏金入袋。',
  },
};
