(()=>{
'use strict';
const R=window.BoardRules,canvas=document.getElementById('board'),ctx=canvas.getContext('2d');
const statusEl=document.getElementById('status'),gameName=document.getElementById('gameName'),hint=document.getElementById('ruleHint'),moveCount=document.getElementById('moveCount');
const restartBtn=document.getElementById('restartBtn'),undoBtn=document.getElementById('undoBtn'),passBtn=document.getElementById('passBtn'),sizeWrap=document.getElementById('goSizeWrap'),sizeSelect=document.getElementById('goSize'),soundBtn=document.getElementById('soundBtn');
let mode='gomoku',board,turn='b',winner=null,selected=null,targets=[],history=[],last=null,passes=0,captures={b:0,w:0},soundOn=true,audio=null;
const names={gomoku:'五子棋',xiangqi:'中国象棋',go:'围棋'};
function clickSound(freq=240,dur=.045){if(!soundOn)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch{}}
function reset(){winner=null;selected=null;targets=[];history=[];last=null;passes=0;captures={b:0,w:0};turn=mode==='xiangqi'?'r':'b';board=mode==='gomoku'?R.gomokuBoard():mode==='xiangqi'?R.xiangqiBoard():R.goBoard(+sizeSelect.value);snapshot();sync();draw()}
function snapshot(){history.push({board:R.clone(board),turn,winner,selected:selected&&{...selected},last:last&&{...last},passes,captures:{...captures}})}
function restore(s){board=R.clone(s.board);turn=s.turn;winner=s.winner;selected=s.selected;last=s.last;passes=s.passes;captures={...s.captures};targets=selected&&mode==='xiangqi'?R.xiangqiTargets(board,selected.x,selected.y):[];sync();draw()}
function sync(){gameName.textContent=names[mode];moveCount.textContent=Math.max(0,history.length-1)+' 手';passBtn.hidden=mode!=='go';sizeWrap.hidden=mode!=='go';
  if(mode==='gomoku'){hint.textContent='自由规则：先连成五子者胜。';statusEl.textContent=winner?(winner==='b'?'黑方胜':'白方胜'):(turn==='b'?'黑方落子':'白方落子')}
  if(mode==='xiangqi'){hint.textContent='标准基础规则：不能送将，支持将帅照面与完整棋子走法。';if(winner)statusEl.textContent=winner==='r'?'红方胜':'黑方胜';else statusEl.textContent=(turn==='r'?'红方':'黑方')+(R.xiangqiInCheck(board,turn)?' · 将军':'走棋')}
  if(mode==='go'){hint.textContent=`中国面积计分 · 黑提 ${captures.b} · 白提 ${captures.w} · 双方连续停一手结束`;statusEl.textContent=winner?winner:(turn==='b'?'黑方落子':'白方落子')}
}
function resize(){const wrap=canvas.parentElement,w=Math.min(wrap.clientWidth-2,mode==='xiangqi'?720:820),ratio=mode==='xiangqi'?10/9:1,cssH=Math.round(w*ratio);canvas.style.width=w+'px';canvas.style.height=cssH+'px';const dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(w*dpr);canvas.height=Math.round(cssH*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function geom(){const w=parseFloat(canvas.style.width)||700,h=parseFloat(canvas.style.height)||700;if(mode==='xiangqi'){const m=Math.max(28,w*.065),sx=(w-2*m)/8,sy=(h-2*m)/9;return{w,h,m,sx,sy,nx:9,ny:10}}const n=board.length,m=Math.max(22,w*.05),s=(w-2*m)/(n-1);return{w,h,m,sx:s,sy:s,nx:n,ny:n}}
function paper(g){ctx.clearRect(0,0,g.w,g.h);const grad=ctx.createLinearGradient(0,0,g.w,g.h);grad.addColorStop(0,'#e6c57f');grad.addColorStop(1,'#c99f57');ctx.fillStyle=grad;ctx.fillRect(0,0,g.w,g.h);ctx.fillStyle='rgba(90,55,18,.05)';for(let i=0;i<18;i++)ctx.fillRect((i*83)%g.w,0,1,g.h)}
function drawGrid(g){ctx.strokeStyle='#5a3a1d';ctx.lineWidth=1.1;ctx.beginPath();for(let x=0;x<g.nx;x++){const px=g.m+x*g.sx;ctx.moveTo(px,g.m);ctx.lineTo(px,g.m+(g.ny-1)*g.sy)}for(let y=0;y<g.ny;y++){const py=g.m+y*g.sy;ctx.moveTo(g.m,py);ctx.lineTo(g.m+(g.nx-1)*g.sx,py)}ctx.stroke()}
function stone(x,y,color,g,r=.43){const px=g.m+x*g.sx,py=g.m+y*g.sy,rad=Math.min(g.sx,g.sy)*r,grad=ctx.createRadialGradient(px-rad*.35,py-rad*.35,rad*.1,px,py,rad);if(color==='b'){grad.addColorStop(0,'#555');grad.addColorStop(.45,'#202020');grad.addColorStop(1,'#050505')}else{grad.addColorStop(0,'#fff');grad.addColorStop(.65,'#eee9dc');grad.addColorStop(1,'#bdb7aa')}ctx.fillStyle=grad;ctx.beginPath();ctx.arc(px,py,rad,0,Math.PI*2);ctx.fill();ctx.strokeStyle=color==='b'?'#000':'#999';ctx.lineWidth=.8;ctx.stroke()}
function markLast(g){if(!last)return;const px=g.m+last.x*g.sx,py=g.m+last.y*g.sy;ctx.fillStyle=mode==='xiangqi'?'#1f6f54':'#b33124';ctx.beginPath();ctx.arc(px,py,Math.max(2,Math.min(g.sx,g.sy)*.08),0,Math.PI*2);ctx.fill()}
function drawGomoku(g){drawGrid(g);const stars=[3,7,11];ctx.fillStyle='#51351d';for(const y of stars)for(const x of stars){ctx.beginPath();ctx.arc(g.m+x*g.sx,g.m+y*g.sy,2.4,0,Math.PI*2);ctx.fill()}for(let y=0;y<15;y++)for(let x=0;x<15;x++)if(board[y][x])stone(x,y,board[y][x],g);markLast(g)}
function drawGo(g){drawGrid(g);const n=board.length,pts=n===19?[3,9,15]:n===13?[3,6,9]:[2,4,6];ctx.fillStyle='#51351d';for(const y of pts)for(const x of pts){ctx.beginPath();ctx.arc(g.m+x*g.sx,g.m+y*g.sy,Math.max(1.7,g.sx*.08),0,Math.PI*2);ctx.fill()}for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(board[y][x])stone(x,y,board[y][x],g,.46);markLast(g)}
const glyph={R:'车',N:'马',B:'相',A:'仕',K:'帅',C:'炮',P:'兵',r:'车',n:'马',b:'象',a:'士',k:'将',c:'炮',p:'卒'};
function drawXiangqi(g){paper(g);ctx.strokeStyle='#56371d';ctx.lineWidth=1.25;for(let y=0;y<10;y++){const py=g.m+y*g.sy;ctx.beginPath();ctx.moveTo(g.m,py);ctx.lineTo(g.m+8*g.sx,py);ctx.stroke()}for(let x=0;x<9;x++){const px=g.m+x*g.sx;ctx.beginPath();ctx.moveTo(px,g.m);ctx.lineTo(px,g.m+4*g.sy);ctx.moveTo(px,g.m+5*g.sy);ctx.lineTo(px,g.m+9*g.sy);ctx.stroke()}ctx.beginPath();ctx.moveTo(g.m+3*g.sx,g.m);ctx.lineTo(g.m+5*g.sx,g.m+2*g.sy);ctx.moveTo(g.m+5*g.sx,g.m);ctx.lineTo(g.m+3*g.sx,g.m+2*g.sy);ctx.moveTo(g.m+3*g.sx,g.m+7*g.sy);ctx.lineTo(g.m+5*g.sx,g.m+9*g.sy);ctx.moveTo(g.m+5*g.sx,g.m+7*g.sy);ctx.lineTo(g.m+3*g.sx,g.m+9*g.sy);ctx.stroke();ctx.fillStyle='rgba(93,55,22,.78)';ctx.font=`${Math.max(15,g.sx*.28)}px "Noto Serif SC","Songti SC",serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('楚 河',g.m+2*g.sx,g.m+4.5*g.sy);ctx.fillText('汉 界',g.m+6*g.sx,g.m+4.5*g.sy);
  for(const t of targets){ctx.fillStyle='rgba(26,103,76,.25)';ctx.beginPath();ctx.arc(g.m+t.x*g.sx,g.m+t.y*g.sy,Math.min(g.sx,g.sy)*.18,0,Math.PI*2);ctx.fill()}
  for(let y=0;y<10;y++)for(let x=0;x<9;x++){const p=board[y][x];if(!p)continue;const px=g.m+x*g.sx,py=g.m+y*g.sy,rad=Math.min(g.sx,g.sy)*.39;ctx.fillStyle='#f5dfb2';ctx.beginPath();ctx.arc(px,py,rad,0,Math.PI*2);ctx.fill();ctx.lineWidth=selected&&selected.x===x&&selected.y===y?3:1.5;ctx.strokeStyle=p.c==='r'?'#a12820':'#30271e';ctx.stroke();ctx.fillStyle=p.c==='r'?'#a12820':'#30271e';ctx.font=`700 ${Math.max(17,rad*1.08)}px "Noto Serif SC","Songti SC",serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(glyph[p.t],px,py+1)}markLast(g)}
function draw(){if(!board)return;const g=geom();if(mode!=='xiangqi')paper(g);if(mode==='gomoku')drawGomoku(g);else if(mode==='xiangqi')drawXiangqi(g);else drawGo(g)}
function point(ev){const r=canvas.getBoundingClientRect(),g=geom(),mx=(ev.clientX-r.left)*(g.w/r.width),my=(ev.clientY-r.top)*(g.h/r.height),x=Math.round((mx-g.m)/g.sx),y=Math.round((my-g.m)/g.sy);return{x,y,g}}
function onGomoku(x,y){if(winner||x<0||y<0||x>=15||y>=15||board[y][x])return;board[y][x]=turn;last={x,y};clickSound(turn==='b'?190:285);if(R.gomokuWin(board,x,y,turn))winner=turn;else turn=turn==='b'?'w':'b';snapshot();sync();draw()}
function onXiangqi(x,y){if(winner||x<0||y<0||x>8||y>9)return;const p=board[y][x];if(!selected){if(p&&p.c===turn){selected={x,y};targets=R.xiangqiTargets(board,x,y);draw()}return}if(p&&p.c===turn){selected={x,y};targets=R.xiangqiTargets(board,x,y);draw();return}const moved=R.xiangqiMove(board,selected.x,selected.y,x,y);if(!moved)return;const captured=moved.captured;board=moved.board;last={x,y};clickSound(captured?150:230);const movedColor=turn,enemy=turn==='r'?'b':'r';selected=null;targets=[];if(captured&&captured.t.toUpperCase()==='K')winner=movedColor;else if(!R.xiangqiHasMove(board,enemy))winner=R.xiangqiInCheck(board,enemy)?movedColor:'draw';else turn=enemy;snapshot();sync();draw()}
function onGo(x,y){if(winner||x<0||y<0||y>=board.length||x>=board.length)return;const koKey=history.length>=2?R.boardKey(history[history.length-2].board):null,res=R.goPlay(board,x,y,turn,koKey);if(!res.ok){statusEl.textContent=res.reason==='ko'?'劫争：此处暂不可立即回提':res.reason==='suicide'?'禁自杀：此处无气':'该点已有棋子';clickSound(100,.07);return}board=res.board;captures[turn]+=res.captured;last={x,y};passes=0;clickSound(res.captured?155:245);turn=turn==='b'?'w':'b';snapshot();sync();draw()}
canvas.addEventListener('pointerup',ev=>{const{x,y}=point(ev);if(mode==='gomoku')onGomoku(x,y);else if(mode==='xiangqi')onXiangqi(x,y);else onGo(x,y)});
document.querySelectorAll('[data-game]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-game]').forEach(b=>b.classList.toggle('active',b===btn));mode=btn.dataset.game;reset();resize()}));
restartBtn.addEventListener('click',reset);undoBtn.addEventListener('click',()=>{if(history.length<=1)return;history.pop();restore(history[history.length-1])});sizeSelect.addEventListener('change',()=>{if(mode==='go')reset()});passBtn.addEventListener('click',()=>{if(mode!=='go'||winner)return;passes++;last=null;clickSound(330);if(passes>=2){const s=R.goScore(board);winner=`终局：${s.winner==='b'?'黑':'白'}胜 ${s.margin.toFixed(1)} 目（黑 ${s.black.toFixed(1)} / 白 ${s.white.toFixed(1)}）`}else turn=turn==='b'?'w':'b';snapshot();sync();draw()});soundBtn.addEventListener('click',()=>{soundOn=!soundOn;soundBtn.textContent='声音 '+(soundOn?'开':'关');soundBtn.setAttribute('aria-pressed',String(soundOn));if(soundOn)clickSound()});window.addEventListener('resize',resize,{passive:true});
reset();resize();document.documentElement.dataset.gameVersion='0.1.0';
})();
