(()=>{
'use strict';
const R=window.BoardRules,canvas=document.getElementById('board'),ctx=canvas.getContext('2d');
const statusEl=document.getElementById('status'),gameName=document.getElementById('gameName'),hint=document.getElementById('ruleHint'),moveCount=document.getElementById('moveCount'),noticeEl=document.getElementById('notice'),sessionHint=document.getElementById('sessionHint');
const restartBtn=document.getElementById('restartBtn'),undoBtn=document.getElementById('undoBtn'),passBtn=document.getElementById('passBtn'),sizeWrap=document.getElementById('goSizeWrap'),sizeSelect=document.getElementById('goSize'),soundBtn=document.getElementById('soundBtn');
const names={gomoku:'五子棋',xiangqi:'中国象棋',go:'围棋'},sessions=Object.create(null);
let mode='gomoku',board,turn='b',winner=null,selected=null,targets=[],history=[],last=null,passes=0,captures={b:0,w:0},cursor=null,activeKey='',audio=null,noticeTimer=0,restartArmed=false,restartTimer=0;
let soundOn=readSoundPreference();

function readSoundPreference(){try{return localStorage.getItem('board-trio-sound-v1')!=='off'}catch{return true}}
function saveSoundPreference(){try{localStorage.setItem('board-trio-sound-v1',soundOn?'on':'off')}catch{}}
function clickSound(freq=240,dur=.045){if(!soundOn)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch{}}
function sessionKey(){return mode==='go'?`go:${sizeSelect.value}`:mode}
function saveSession(key=activeKey){if(!key||!board)return;sessions[key]={board,turn,winner,selected,targets,history,last,passes,captures,cursor}}
function loadSession(key){const s=sessions[key];if(!s)return false;board=s.board;turn=s.turn;winner=s.winner;selected=s.selected;targets=s.targets;history=s.history;last=s.last;passes=s.passes;captures=s.captures;cursor=s.cursor;return true}
function freshBoard(){winner=null;selected=null;targets=[];history=[];last=null;passes=0;captures={b:0,w:0};cursor=null;turn=mode==='xiangqi'?'r':'b';board=mode==='gomoku'?R.gomokuBoard():mode==='xiangqi'?R.xiangqiBoard():R.goBoard(+sizeSelect.value);snapshot()}
function reset(){freshBoard();sessions[activeKey]={board,turn,winner,selected,targets,history,last,passes,captures,cursor};cancelRestart();clearNotice();sync();draw()}
function snapshot(){history.push({board:R.clone(board),turn,winner,selected:selected&&{...selected},last:last&&{...last},passes,captures:{...captures}})}
function restore(s){board=R.clone(s.board);turn=s.turn;winner=s.winner;selected=s.selected&&{...s.selected};last=s.last&&{...s.last};passes=s.passes;captures={...s.captures};targets=selected&&mode==='xiangqi'?R.xiangqiTargets(board,selected.x,selected.y):[];cursor=last?{...last}:cursor;sync();draw()}
function showNotice(text,tone='info',ms=1800){clearTimeout(noticeTimer);noticeEl.hidden=false;noticeEl.dataset.tone=tone;noticeEl.textContent=text;noticeTimer=setTimeout(clearNotice,ms)}
function clearNotice(){clearTimeout(noticeTimer);noticeEl.hidden=true;noticeEl.textContent=''}
function cancelRestart(){clearTimeout(restartTimer);restartArmed=false;restartBtn.classList.remove('armed');restartBtn.textContent='重开'}
function armRestart(){if(history.length<=1){reset();return}if(restartArmed){reset();showNotice('已开始新局','ok');return}restartArmed=true;restartBtn.classList.add('armed');restartBtn.textContent='再点一次重开';showNotice('再次点击“重开”才会清空当前对局','warn',2200);restartTimer=setTimeout(cancelRestart,2200)}
function syncUrl(){const url=new URL(location.href);url.searchParams.set('game',mode);if(mode==='go')url.searchParams.set('size',sizeSelect.value);else url.searchParams.delete('size');window.history.replaceState(null,'',url)}
function sync(){gameName.textContent=names[mode];moveCount.textContent=Math.max(0,history.length-1)+' 手';passBtn.hidden=mode!=='go';sizeWrap.hidden=mode!=='go';undoBtn.disabled=history.length<=1;restartBtn.disabled=history.length<=1;sessionHint.textContent='切换棋类会保留本页内的当前对局';
  if(mode==='gomoku'){hint.textContent='自由规则：先连成五子者胜。';statusEl.textContent=winner?(winner==='draw'?'和棋':winner==='b'?'黑方胜':'白方胜'):(turn==='b'?'黑方落子':'白方落子')}
  if(mode==='xiangqi'){hint.textContent='标准基础规则：不能送将；支持将帅照面、困毙与完整棋子走法。';if(winner)statusEl.textContent=winner==='r'?'红方胜':'黑方胜';else statusEl.textContent=(turn==='r'?'红方':'黑方')+(R.xiangqiInCheck(board,turn)?' · 将军':'走棋')}
  if(mode==='go'){hint.textContent=`中国面积计分 · 贴目 7.5 · 黑提 ${captures.b} · 白提 ${captures.w} · 连续停一手两次后自动估算`;statusEl.textContent=winner?winner:(turn==='b'?'黑方落子':'白方落子')}
  soundBtn.textContent='声音 '+(soundOn?'开':'关');soundBtn.setAttribute('aria-pressed',String(soundOn));
  canvas.setAttribute('aria-label',`${names[mode]}棋盘。${statusEl.textContent}。方向键移动焦点，回车或空格落子或走棋。`);
}
function resize(){const wrap=canvas.parentElement,w=Math.max(240,Math.min(wrap.clientWidth-2,mode==='xiangqi'?720:820)),ratio=mode==='xiangqi'?10/9:1,cssH=Math.round(w*ratio);canvas.style.width=w+'px';canvas.style.height=cssH+'px';const dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(w*dpr);canvas.height=Math.round(cssH*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function geom(){const w=parseFloat(canvas.style.width)||700,h=parseFloat(canvas.style.height)||700;if(mode==='xiangqi'){const m=Math.max(28,w*.065),sx=(w-2*m)/8,sy=(h-2*m)/9;return{w,h,m,sx,sy,nx:9,ny:10}}const n=board.length,m=Math.max(22,w*.05),s=(w-2*m)/(n-1);return{w,h,m,sx:s,sy:s,nx:n,ny:n}}
function paper(g){ctx.clearRect(0,0,g.w,g.h);const grad=ctx.createLinearGradient(0,0,g.w,g.h);grad.addColorStop(0,'#e6c57f');grad.addColorStop(1,'#c99f57');ctx.fillStyle=grad;ctx.fillRect(0,0,g.w,g.h);ctx.fillStyle='rgba(90,55,18,.05)';for(let i=0;i<18;i++)ctx.fillRect((i*83)%g.w,0,1,g.h)}
function drawGrid(g){ctx.strokeStyle='#5a3a1d';ctx.lineWidth=1.1;ctx.beginPath();for(let x=0;x<g.nx;x++){const px=g.m+x*g.sx;ctx.moveTo(px,g.m);ctx.lineTo(px,g.m+(g.ny-1)*g.sy)}for(let y=0;y<g.ny;y++){const py=g.m+y*g.sy;ctx.moveTo(g.m,py);ctx.lineTo(g.m+(g.nx-1)*g.sx,py)}ctx.stroke()}
function stone(x,y,color,g,r=.43,alpha=1){const px=g.m+x*g.sx,py=g.m+y*g.sy,rad=Math.min(g.sx,g.sy)*r,grad=ctx.createRadialGradient(px-rad*.35,py-rad*.35,rad*.1,px,py,rad);ctx.save();ctx.globalAlpha=alpha;if(color==='b'){grad.addColorStop(0,'#555');grad.addColorStop(.45,'#202020');grad.addColorStop(1,'#050505')}else{grad.addColorStop(0,'#fff');grad.addColorStop(.65,'#eee9dc');grad.addColorStop(1,'#bdb7aa')}ctx.fillStyle=grad;ctx.beginPath();ctx.arc(px,py,rad,0,Math.PI*2);ctx.fill();ctx.strokeStyle=color==='b'?'#000':'#999';ctx.lineWidth=.8;ctx.stroke();ctx.restore()}
function markLast(g){if(!last)return;const px=g.m+last.x*g.sx,py=g.m+last.y*g.sy,rad=Math.max(3,Math.min(g.sx,g.sy)*.11);ctx.save();ctx.fillStyle=mode==='xiangqi'?'#1f6f54':'#b33124';ctx.beginPath();ctx.arc(px,py,rad,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawCursor(g){if(!cursor||winner)return;const{x,y}=cursor;if(x<0||y<0||x>=g.nx||y>=g.ny)return;const px=g.m+x*g.sx,py=g.m+y*g.sy,rad=Math.max(8,Math.min(g.sx,g.sy)*.38);ctx.save();ctx.strokeStyle='rgba(27,91,70,.95)';ctx.lineWidth=2;ctx.setLineDash([4,3]);ctx.beginPath();ctx.arc(px,py,rad,0,Math.PI*2);ctx.stroke();ctx.restore();if(mode!=='xiangqi'&&!board[y][x])stone(x,y,turn,g,mode==='go'?.46:.43,.24)}
function drawGomoku(g){drawGrid(g);const stars=[3,7,11];ctx.fillStyle='#51351d';for(const y of stars)for(const x of stars){ctx.beginPath();ctx.arc(g.m+x*g.sx,g.m+y*g.sy,2.4,0,Math.PI*2);ctx.fill()}for(let y=0;y<15;y++)for(let x=0;x<15;x++)if(board[y][x])stone(x,y,board[y][x],g);markLast(g);drawCursor(g)}
function drawGo(g){drawGrid(g);const n=board.length,pts=n===19?[3,9,15]:n===13?[3,6,9]:[2,4,6];ctx.fillStyle='#51351d';for(const y of pts)for(const x of pts){ctx.beginPath();ctx.arc(g.m+x*g.sx,g.m+y*g.sy,Math.max(1.7,g.sx*.08),0,Math.PI*2);ctx.fill()}for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(board[y][x])stone(x,y,board[y][x],g,.46);markLast(g);drawCursor(g)}
const glyph={R:'车',N:'马',B:'相',A:'仕',K:'帅',C:'炮',P:'兵',r:'车',n:'马',b:'象',a:'士',k:'将',c:'炮',p:'卒'};
function drawXiangqi(g){paper(g);ctx.strokeStyle='#56371d';ctx.lineWidth=1.25;for(let y=0;y<10;y++){const py=g.m+y*g.sy;ctx.beginPath();ctx.moveTo(g.m,py);ctx.lineTo(g.m+8*g.sx,py);ctx.stroke()}for(let x=0;x<9;x++){const px=g.m+x*g.sx;ctx.beginPath();ctx.moveTo(px,g.m);ctx.lineTo(px,g.m+4*g.sy);ctx.moveTo(px,g.m+5*g.sy);ctx.lineTo(px,g.m+9*g.sy);ctx.stroke()}ctx.beginPath();ctx.moveTo(g.m+3*g.sx,g.m);ctx.lineTo(g.m+5*g.sx,g.m+2*g.sy);ctx.moveTo(g.m+5*g.sx,g.m);ctx.lineTo(g.m+3*g.sx,g.m+2*g.sy);ctx.moveTo(g.m+3*g.sx,g.m+7*g.sy);ctx.lineTo(g.m+5*g.sx,g.m+9*g.sy);ctx.moveTo(g.m+5*g.sx,g.m+7*g.sy);ctx.lineTo(g.m+3*g.sx,g.m+9*g.sy);ctx.stroke();ctx.fillStyle='rgba(93,55,22,.78)';ctx.font=`${Math.max(15,g.sx*.28)}px "Noto Serif SC","Songti SC",serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('楚 河',g.m+2*g.sx,g.m+4.5*g.sy);ctx.fillText('汉 界',g.m+6*g.sx,g.m+4.5*g.sy);
  for(const t of targets){const capture=!!board[t.y][t.x];ctx.fillStyle=capture?'rgba(151,50,38,.2)':'rgba(26,103,76,.25)';ctx.strokeStyle=capture?'rgba(151,50,38,.9)':'rgba(26,103,76,.8)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(g.m+t.x*g.sx,g.m+t.y*g.sy,Math.min(g.sx,g.sy)*(capture?.29:.18),0,Math.PI*2);capture?ctx.stroke():ctx.fill()}
  for(let y=0;y<10;y++)for(let x=0;x<9;x++){const p=board[y][x];if(!p)continue;const px=g.m+x*g.sx,py=g.m+y*g.sy,rad=Math.min(g.sx,g.sy)*.39;ctx.fillStyle='#f5dfb2';ctx.beginPath();ctx.arc(px,py,rad,0,Math.PI*2);ctx.fill();ctx.lineWidth=selected&&selected.x===x&&selected.y===y?3:1.5;ctx.strokeStyle=p.c==='r'?'#a12820':'#30271e';ctx.stroke();ctx.fillStyle=p.c==='r'?'#a12820':'#30271e';ctx.font=`700 ${Math.max(17,rad*1.08)}px "Noto Serif SC","Songti SC",serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(glyph[p.t],px,py+1)}markLast(g);drawCursor(g)}
function draw(){if(!board)return;const g=geom();if(mode!=='xiangqi')paper(g);if(mode==='gomoku')drawGomoku(g);else if(mode==='xiangqi')drawXiangqi(g);else drawGo(g)}
function point(ev){const r=canvas.getBoundingClientRect(),g=geom(),mx=(ev.clientX-r.left)*(g.w/r.width),my=(ev.clientY-r.top)*(g.h/r.height),x=Math.round((mx-g.m)/g.sx),y=Math.round((my-g.m)/g.sy);return{x,y,g}}
function insidePoint(x,y){const g=geom();return x>=0&&y>=0&&x<g.nx&&y<g.ny}
function onGomoku(x,y){if(winner||!insidePoint(x,y))return false;if(board[y][x]){showNotice('这里已经有棋子','warn');return false}board[y][x]=turn;last={x,y};cursor={x,y};clickSound(turn==='b'?190:285);if(R.gomokuWin(board,x,y,turn)){winner=turn;showNotice((turn==='b'?'黑方':'白方')+'连成五子','ok',2600)}else if(R.gomokuFull(board)){winner='draw';showNotice('棋盘已满，本局和棋','ok',2600)}else turn=turn==='b'?'w':'b';snapshot();sync();draw();return true}
function onXiangqi(x,y){if(winner||!insidePoint(x,y))return false;cursor={x,y};const p=board[y][x];if(!selected){if(p&&p.c===turn){selected={x,y};targets=R.xiangqiTargets(board,x,y);draw();return true}showNotice('请选择己方棋子','warn');draw();return false}if(p&&p.c===turn){selected={x,y};targets=R.xiangqiTargets(board,x,y);draw();return true}const moved=R.xiangqiMove(board,selected.x,selected.y,x,y);if(!moved){showNotice('此走法不合法','warn');draw();return false}const captured=moved.captured;board=moved.board;last={x,y};clickSound(captured?150:230);const movedColor=turn,enemy=turn==='r'?'b':'r';selected=null;targets=[];if(captured&&captured.t.toUpperCase()==='K'){winner=movedColor;showNotice((movedColor==='r'?'红方':'黑方')+'获胜','ok',2600)}else{const terminal=R.xiangqiTerminal(board,enemy);if(terminal){winner=movedColor;showNotice(terminal==='stalemate'?'困毙，'+(movedColor==='r'?'红方':'黑方')+'胜':'将死，'+(movedColor==='r'?'红方':'黑方')+'胜','ok',2600)}else turn=enemy}snapshot();sync();draw();return true}
function onGo(x,y){if(winner||!insidePoint(x,y))return false;cursor={x,y};const koKey=history.length>=2?R.boardKey(history[history.length-2].board):null,res=R.goPlay(board,x,y,turn,koKey);if(!res.ok){showNotice(res.reason==='ko'?'劫争：此处暂不可立即回提':res.reason==='suicide'?'禁自杀：此处无气':'该点已有棋子','warn');clickSound(100,.07);draw();return false}board=res.board;captures[turn]+=res.captured;last={x,y};passes=0;clickSound(res.captured?155:245);if(res.captured)showNotice(`提子 ${res.captured} 枚`,'ok');turn=turn==='b'?'w':'b';snapshot();sync();draw();return true}
function actAt(x,y){if(mode==='gomoku')return onGomoku(x,y);if(mode==='xiangqi')return onXiangqi(x,y);return onGo(x,y)}
function defaultCursor(){const g=geom();return{x:Math.floor((g.nx-1)/2),y:mode==='xiangqi'?6:Math.floor((g.ny-1)/2)}}
function switchGame(next){if(next===mode)return;saveSession();cancelRestart();clearNotice();mode=next;activeKey=sessionKey();const restored=loadSession(activeKey);if(!restored)freshBoard();syncUrl();sync();resize();showNotice(restored&&history.length>1?'已恢复这类棋的当前对局':'已切换至'+names[mode],'ok')}
canvas.addEventListener('pointerup',ev=>{const{x,y}=point(ev);cursor={x,y};actAt(x,y)});
canvas.addEventListener('pointermove',ev=>{if(ev.pointerType!=='mouse'&&ev.pointerType!=='pen')return;const{x,y}=point(ev);if(!insidePoint(x,y))return;if(!cursor||cursor.x!==x||cursor.y!==y){cursor={x,y};draw()}});
canvas.addEventListener('pointerleave',ev=>{if(ev.pointerType==='mouse'&&document.activeElement!==canvas){cursor=null;draw()}});
canvas.addEventListener('focus',()=>{if(!cursor)cursor=last?{...last}:defaultCursor();draw()});
canvas.addEventListener('keydown',ev=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter',' '].includes(ev.key))return;ev.preventDefault();if(!cursor)cursor=last?{...last}:defaultCursor();const g=geom();if(ev.key==='ArrowLeft')cursor.x=Math.max(0,cursor.x-1);else if(ev.key==='ArrowRight')cursor.x=Math.min(g.nx-1,cursor.x+1);else if(ev.key==='ArrowUp')cursor.y=Math.max(0,cursor.y-1);else if(ev.key==='ArrowDown')cursor.y=Math.min(g.ny-1,cursor.y+1);else actAt(cursor.x,cursor.y);draw()});
document.querySelectorAll('[data-game]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-game]').forEach(b=>b.classList.toggle('active',b===btn));switchGame(btn.dataset.game)}));
restartBtn.addEventListener('click',armRestart);
undoBtn.addEventListener('click',()=>{cancelRestart();if(history.length<=1)return;history.pop();restore(history[history.length-1]);showNotice('已悔棋','ok')});
sizeSelect.addEventListener('change',()=>{if(mode!=='go')return;saveSession();cancelRestart();clearNotice();activeKey=sessionKey();const restored=loadSession(activeKey);if(!restored)freshBoard();syncUrl();sync();resize();showNotice(restored&&history.length>1?`已恢复 ${sizeSelect.value}×${sizeSelect.value} 对局`:`已切换为 ${sizeSelect.value}×${sizeSelect.value} 棋盘`,'ok')});
passBtn.addEventListener('click',()=>{if(mode!=='go'||winner)return;cancelRestart();passes++;last=null;cursor=cursor||defaultCursor();clickSound(330);if(passes>=2){const s=R.goScore(board);winner=`终局估算：${s.winner==='b'?'黑':'白'}胜 ${s.margin.toFixed(1)} 目（黑 ${s.black.toFixed(1)} / 白 ${s.white.toFixed(1)}）`;showNotice('双方连续停一手，已按当前盘面自动估算','ok',2800)}else{turn=turn==='b'?'w':'b';showNotice('已停一手；对方再停一手将进入自动估算','info',2200)}snapshot();sync();draw()});
soundBtn.addEventListener('click',()=>{soundOn=!soundOn;saveSoundPreference();sync();if(soundOn)clickSound();showNotice('声音已'+(soundOn?'开启':'关闭'),'ok')});
window.addEventListener('resize',resize,{passive:true});

const qs=new URLSearchParams(location.search),requested=qs.get('game'),requestedSize=+qs.get('size');if(names[requested])mode=requested;if([9,13,19].includes(requestedSize))sizeSelect.value=String(requestedSize);activeKey=sessionKey();freshBoard();syncUrl();document.querySelectorAll('[data-game]').forEach(b=>b.classList.toggle('active',b.dataset.game===mode));
canvas.tabIndex=0;reset();resize();document.documentElement.dataset.gameVersion='0.2.0';
})();
