'use strict';
const assert=require('assert');
const fs=require('fs');
const [,,indexPath,gamePath]=process.argv;
assert(indexPath&&gamePath,'usage: node build-v1113.cjs <index.html> <game.js>');
const replaceOnce=(text,from,to,label)=>{const first=text.indexOf(from);assert(first>=0,`missing ${label}`);assert.equal(text.indexOf(from,first+from.length),-1,`duplicate ${label}`);return text.slice(0,first)+to+text.slice(first+from.length)};
let index=fs.readFileSync(indexPath,'utf8');
const prepaint=`<meta name="google" content="notranslate" />\n<script>(()=>{try{const r=document.documentElement,q=new URLSearchParams(location.search),c=n=>{const x=document.cookie.split('; ').find(v=>v.startsWith(n+'='));return x?decodeURIComponent(x.slice(n.length+1)):''};let l=q.get('lang');if(l!=='zh'&&l!=='en')l=c('91hwl_lang')||localStorage.getItem('91hwl_lang')||((navigator.language||'').toLowerCase().startsWith('zh')?'zh':'en');r.dataset.lang=l;r.lang=l==='en'?'en':'zh-CN';r.classList.add('notranslate');r.setAttribute('translate','no')}catch(_){}})();</script>`;
index=replaceOnce(index,'<html lang="zh-CN" data-lang="zh">','<html lang="zh-CN" data-lang="zh" class="notranslate" translate="no">','html prepaint marker');
index=replaceOnce(index,'<meta name="theme-color" content="#f3f0e8" />','<meta name="theme-color" content="#f3f0e8" />\n'+prepaint,'prepaint insertion');
index=replaceOnce(index,'<meta name="version" content="1.11.2" />','<meta name="version" content="1.11.3" />','version meta');
index=replaceOnce(index,'style.css?v=1112','style.css?v=1113','base css fingerprint');
index=replaceOnce(index,'visual-v1112.css?v=1112','visual-v1113.css?v=1113','visual css fingerprint');
index=replaceOnce(index,'<span class="version-badge">v1.11.2</span>','<span class="version-badge">v1.11.3</span>','visible version badge');
index=replaceOnce(index,'91HWL / CLOCK OUT ALIVE / v1.11.2','91HWL / CLOCK OUT ALIVE / v1.11.3','footer version');
index=replaceOnce(index,'game.js?v=1112','game.js?v=1113','game fingerprint');
let game=fs.readFileSync(gamePath,'utf8');
game=replaceOnce(game,"dataset.gameVersion='1.11.2'","dataset.gameVersion='1.11.3'",'runtime version');
assert(index.includes('translate="no"'));
assert(index.includes('name="google" content="notranslate"'));
assert(index.includes('visual-v1113.css?v=1113'));
assert(game.includes("dataset.gameVersion='1.11.3'"));
fs.writeFileSync(indexPath,index);
fs.writeFileSync(gamePath,game);
