'use strict';
const assert=require('assert');
const fs=require('fs');
const [,,indexPath,gamePath]=process.argv;
assert(indexPath&&gamePath,'usage: node build-v1114.cjs <index.html> <game.js>');
const replaceOnce=(text,from,to,label)=>{const first=text.indexOf(from);assert(first>=0,`missing ${label}`);assert.equal(text.indexOf(from,first+from.length),-1,`duplicate ${label}`);return text.slice(0,first)+to+text.slice(first+from.length)};
let index=fs.readFileSync(indexPath,'utf8');
index=replaceOnce(index,'<meta name="version" content="1.11.3" />','<meta name="version" content="1.11.4" />','version meta');
index=replaceOnce(index,'style.css?v=1113','style.css?v=1114','base css fingerprint');
index=replaceOnce(index,'visual-v1113.css?v=1113','visual-v1113.css?v=1114','visual css fingerprint');
index=replaceOnce(index,'<span class="version-badge">v1.11.3</span>','<span class="version-badge">v1.11.4</span>','visible version badge');
index=replaceOnce(index,'91HWL / CLOCK OUT ALIVE / v1.11.3','91HWL / CLOCK OUT ALIVE / v1.11.4','footer version');
index=replaceOnce(index,'game.js?v=1113','game.js?v=1114','game fingerprint');
const game=fs.readFileSync(gamePath,'utf8');
assert(game.includes("dataset.gameVersion='1.11.4'"),'runtime version missing');
assert(game.includes('repeatSensitiveKeys'),'keyboard repeat guard missing');
assert(game.includes('canvasLayoutDirty'),'canvas layout invalidation guard missing');
assert(game.includes('syncPresentationState.signature'),'presentation-state memoization missing');
assert(game.includes('effectiveSpawnWidth(spawned)'),'spawn-width fairness guard missing');
assert(index.includes('translate="no"'));
assert(index.includes('name="google" content="notranslate"'));
assert(index.includes('visual-v1113.css?v=1114'));
fs.writeFileSync(indexPath,index);
