#!/usr/bin/env bash
set -euo pipefail
repo_root="$(git rev-parse --show-toplevel)"
source_root="$repo_root/moyu"
version="$(tr -d '\r\n' < "$source_root/VERSION")"
[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "invalid Moyu version: $version" >&2; exit 2; }
asset_tag="$(printf '%s' "$version" | tr -d '.')"
revision="$(git -C "$repo_root" rev-parse HEAD)"
output="${1:-$repo_root/91hwl-play-moyu-v$version.zip}"
stage_root="$(mktemp -d)"
bundle="$stage_root/91hwl-play-moyu-v$version"
cleanup(){ rm -rf -- "$stage_root"; }
trap cleanup EXIT
command -v zip >/dev/null
command -v sha256sum >/dev/null
command -v node >/dev/null
release_files=(index.html style.css visual-v1113.css responsive-v1120.css game.js VERSION assets/sprites/hero-v125.webp assets/sprites/hero.json assets/scenes-v126/workstation.svg assets/scenes-v126/meeting.svg assets/scenes-v126/pantry.svg assets/scenes-v126/gym.svg assets/sprites/office-hazards-v124.webp)
for rel in "${release_files[@]}"; do
  file="$source_root/$rel"
  test -r "$file" || { echo "missing Moyu release source: $rel" >&2; exit 2; }
  git -C "$repo_root" ls-files --error-unmatch "moyu/$rel" >/dev/null 2>&1 || { echo "untracked Moyu release source: $rel" >&2; exit 2; }
done
node --check "$source_root/game.js" >/dev/null
grep -Fq "<meta name=\"version\" content=\"$version\"" "$source_root/index.html"
grep -Fq "style.css?v=$asset_tag" "$source_root/index.html"
grep -Fq "visual-v1113.css?v=$asset_tag" "$source_root/index.html"
grep -Fq "responsive-v1120.css?v=$asset_tag" "$source_root/index.html"
grep -Fq "game.js?v=$asset_tag" "$source_root/index.html"
grep -Fq 'height:min(54svh,440px)' "$source_root/style.css"
grep -Fq 'left:clamp(-28px,-7vw,-18px)' "$source_root/style.css"
grep -Fq 'translate="no"' "$source_root/index.html"
grep -Fq "(cl==='zh'||cl==='en')?cl:((sl==='zh'||sl==='en')?sl:bl)" "$source_root/index.html"
grep -Fq 'viewport-hint' "$source_root/index.html"
grep -Fq 'id="lastRunSummary"' "$source_root/index.html"
grep -Fq 'id="topRunHistory"' "$source_root/index.html"
grep -Fq 'id="dailyBtn"' "$source_root/index.html"
grep -Fq 'id="dailyBadge"' "$source_root/index.html"
grep -Fq 'id="buffChip"' "$source_root/index.html"
grep -Fq 'function syncBuffHud()' "$source_root/game.js"
grep -Fq 'function pickupGrabBox(p)' "$source_root/game.js"
grep -Fq 'LEAVE_SLIP_DURATION=12' "$source_root/game.js"
grep -Fq 'function gameRandom()' "$source_root/game.js"
grep -Fq 'function drawGameFeelFx()' "$source_root/game.js"
grep -Fq 'function updateComboHud()' "$source_root/game.js"
grep -Fq 'BOSS_RUSH_WARNING=.48' "$source_root/game.js"
grep -Fq '.combo-chip:after' "$source_root/style.css"
grep -Fq 'function setDailyMode(enabled)' "$source_root/game.js"
grep -Fq 'dailyModifierDefs' "$source_root/game.js"
grep -Fq "dataset.gameVersion='$version'" "$source_root/game.js"
grep -Fq 'MAX_MISTAKES=3' "$source_root/game.js"
grep -Fq 'function takeObstacleHit(o)' "$source_root/game.js"
grep -Fq 'function applyEncounterCadence(gapPx,plan)' "$source_root/game.js"
grep -Fq 'sceneComboRecoveryUsed' "$source_root/game.js"
grep -Fq 'visualScrollPx+=speed*dt' "$source_root/game.js"
grep -Fq 'display:136' "$source_root/game.js"
! grep -Fq "drawW=frameIndex===HERO_SPRITE.doubleJump?108:size" "$source_root/game.js"
grep -Fq 'MUSIC_PHRASE_STEPS=256' "$source_root/game.js"
grep -Fq "langBtn.blur()" "$source_root/game.js"
grep -Fq "jumpKey&&state==='playing'" "$source_root/game.js"
grep -Fq "if(tutorialActive&&tutorialStep)setTutorial(tutorialStep)" "$source_root/game.js"
grep -Fq "storedNumber('91hwl_moyu_music_vol',42)" "$source_root/game.js"
grep -Fq "storedNumber('91hwl_moyu_sfx_vol',72)" "$source_root/game.js"
grep -Fq 'v1.22 English composition' "$source_root/visual-v1113.css"
grep -Fq "name:'工位区 · 午后摸鱼'" "$source_root/game.js"
grep -Fq "name:'会议室 · 偷偷走神'" "$source_root/game.js"
grep -Fq "name:'茶水间 · 咖啡续杯'" "$source_root/game.js"
grep -Fq "name:'健身房 · 下班冲刺'" "$source_root/game.js"
grep -Fq "if(raw===null||raw==='')return fallback" "$source_root/game.js"
grep -Fq "o.rush&&!o.rushTriggered&&o.x<610" "$source_root/game.js"
grep -Fq "unlockDiscovery(def.discovery,true)" "$source_root/game.js"
grep -Fq 'JUMP_GRAVITY=1750' "$source_root/game.js"
! grep -Fq 'spawnPickupChoice' "$source_root/game.js"
grep -Fq 'DAY_END_DISTANCE=2200' "$source_root/game.js"
grep -Fq 'const groundTakeoff=before===0' "$source_root/game.js"
grep -Fq 'const storedLang=storageGet(LANG_KEY)' "$source_root/game.js"
grep -Fq 'repeatSensitiveKeys' "$source_root/game.js"
grep -Fq 'syncPresentationState.signature' "$source_root/game.js"
grep -Fq 'function viewportFrameMaxWidth' "$source_root/game.js"
grep -Fq 'function fitGameFrameToViewport' "$source_root/game.js"
grep -Fq 'function choosePickupKind' "$source_root/game.js"
grep -Fq 'function nearMissTier' "$source_root/game.js"
grep -Fq 'function absorbWithLeaveSlip' "$source_root/game.js"
grep -Fq 'meetingDrift=sceneIndex===1&&!first' "$source_root/game.js"
grep -Fq 'gymBounce=true' "$source_root/game.js"
grep -Fq "spawnPickup('coffee')" "$source_root/game.js"
grep -Fq 'PERFECT NEAR MISS' "$source_root/game.js"
grep -Fq 'function recordFinishedRun' "$source_root/game.js"
grep -Fq 'function renderRunLedger' "$source_root/game.js"
grep -Fq '91hwl_moyu_top_runs' "$source_root/game.js"
grep -Fq '91hwl_moyu_last_run' "$source_root/game.js"
grep -Fq '.run-ledger-grid' "$source_root/style.css"
grep -Fq 'playfield-first presentation' "$source_root/style.css"
grep -Fq 'const rise=airborne' "$source_root/game.js"
grep -Fq 'const cadence=10.5' "$source_root/game.js"
grep -Fq "assets/sprites/hero-v125.webp?v=1263" "$source_root/game.js"
grep -Fq 'function drawPlayerSprite()' "$source_root/game.js"
grep -Fq 'function heroRunFrameStep()' "$source_root/game.js"
grep -Fq 'player.jumps>=2&&airBurstTimer>0' "$source_root/game.js"
grep -Fq 'RUN_PROGRESS_SCALE=.020' "$source_root/game.js"
grep -Fq 'function drawWorkstationLife(pod)' "$source_root/game.js"
grep -Fq 'function drawMeetingLife(module)' "$source_root/game.js"
grep -Fq 'function drawPantryLife(pod)' "$source_root/game.js"
grep -Fq 'function drawGymLife(pod)' "$source_root/game.js"
grep -Fq 'function drawBossArt(o)' "$source_root/game.js"
grep -Fq 'function drawBugArt(o)' "$source_root/game.js"
grep -Fq 'function drawRequestArt(o)' "$source_root/game.js"
grep -Fq 'function drawSmallHazardArt(o)' "$source_root/game.js"
grep -Fq 'const OFFICE_HAZARD_ATLAS=' "$source_root/game.js"
grep -Fq 'function drawOfficeHazardFrame(name,dx,dy,dw,dh,alpha=1,flipX=false)' "$source_root/game.js"
grep -Fq 'assets/sprites/office-hazards-v124.webp?v=1240' "$source_root/game.js"
grep -Fq 'debugHazardAtlas' "$source_root/game.js"
grep -Fq 'assets/scenes-v126/workstation.svg?v=1263' "$source_root/game.js"
grep -Fq 'function drawAuthenticScene(idx)' "$source_root/game.js"
grep -Fq 'function drawAssetRunway()' "$source_root/game.js"
grep -Fq 'function drawRunnerBackdropClearance(i)' "$source_root/game.js"
grep -Fq 'function drawRunnerSilhouetteHalo(drawX,footY,altitude)' "$source_root/game.js"
grep -Fq 'const srcW=1920,srcTop=82,srcBottom=820,srcFloor=[604,545,442,480][i],worldJoin=[418,414,408,408][i],runwayJoin=GROUND-34' "$source_root/game.js"
grep -Fq 'transform="translate(-120 0)"' "$source_root/assets/scenes-v126/workstation.svg"
grep -Fq 'debugSceneBackdrop' "$source_root/game.js"
grep -Fq 'function drawPlayerVector()' "$source_root/game.js"
test "$(sha256sum "$source_root/assets/sprites/hero-v125.webp" | awk '{print $1}')" = '5db0e3363678341f6f432d7366c0670bc5a0f42be87417d1c43273710364db37'
for f in assets/scenes-v126/workstation.svg assets/scenes-v126/meeting.svg assets/scenes-v126/pantry.svg assets/scenes-v126/gym.svg; do test -s "$source_root/$f"; done
test "$(sha256sum "$source_root/assets/sprites/office-hazards-v124.webp" | awk '{print $1}')" = '93b2583d42dc79a999ddf7f1761067eb9b516249193bbc33412b9bcd8be9ff56'
grep -Fq 'window.visualViewport' "$source_root/game.js"
grep -Fq 'env(safe-area-inset-bottom)' "$source_root/responsive-v1120.css"
grep -Fq '@media(max-width:700px) and (orientation:portrait)' "$source_root/responsive-v1120.css"
grep -Fq 'padding-left:max(2px,env(safe-area-inset-left))' "$source_root/responsive-v1120.css"
mkdir -p "$bundle/public/moyu/assets/sprites" "$bundle/public/moyu/assets/scenes-v126" "$bundle/ops"
for rel in "${release_files[@]}"; do install -m 0644 "$source_root/$rel" "$bundle/public/moyu/$rel"; done
cmp -s "$source_root/game.js" "$bundle/public/moyu/game.js"
cmp -s "$source_root/index.html" "$bundle/public/moyu/index.html"
install -m 0755 "$repo_root/ops/moyu-bundle/deploy.sh" "$bundle/ops/deploy.sh"
install -m 0755 "$repo_root/ops/moyu-bundle/healthcheck.sh" "$bundle/ops/healthcheck.sh"
install -m 0644 "$repo_root/ops/moyu-bundle/README.txt" "$bundle/README.txt"
printf '%s\n' "$version" > "$bundle/VERSION"
printf '%s\n' "$revision" > "$bundle/REVISION"
(cd "$bundle" && find README.txt REVISION VERSION ops public -type f -print0 | sort -z | while IFS= read -r -d '' file; do sha256sum "$file"; done > SHA256SUMS)
mkdir -p "$(dirname "$output")"
rm -f -- "$output"
(cd "$bundle" && zip -q -r "$output" .)
echo "bundle=$output"
echo "version=$version"
echo "revision=$revision"
echo "game_sha256=$(sha256sum "$source_root/game.js" | awk '{print $1}')"
echo 'moyu_bundle_build=PASS'
